# Generated by Django 4.1.3 on 2023-03-20 17:53

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    api.customs.CustomEmailField(
                        help_text="Help Text Placeholder",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=20,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "address",
                    api.customs.CustomTextField(
                        help_text="Help Text Placeholder",
                        max_length=200,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Informations",
            },
        ),
        migrations.CreateModel(
            name="Hours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monday",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        null=True,
                        verbose_name="Monday",
                    ),
                ),
                (
                    "tuesday",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        null=True,
                        verbose_name="Tuesday",
                    ),
                ),
                (
                    "wednesday",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        null=True,
                        verbose_name="Wednesday",
                    ),
                ),
                (
                    "thursday",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        null=True,
                        verbose_name="Thursday",
                    ),
                ),
                (
                    "friday",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        null=True,
                        verbose_name="Friday",
                    ),
                ),
                (
                    "saturday",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        null=True,
                        verbose_name="Saturday",
                    ),
                ),
                (
                    "sunday",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        null=True,
                        verbose_name="Sunday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Hours",
                "verbose_name_plural": "Company Hourss",
            },
        ),
        migrations.CreateModel(
            name="Socials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        null=True,
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "linkedin",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        null=True,
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "instagram",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        null=True,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "twitter",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        null=True,
                        verbose_name="Twitter",
                    ),
                ),
                (
                    "youtube",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        null=True,
                        verbose_name="Youtube",
                    ),
                ),
                (
                    "github",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        null=True,
                        verbose_name="Github",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Socials",
                "verbose_name_plural": "Company Socialss",
            },
        ),
    ]
