# Generated by Django 4.1.3 on 2023-03-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactInformation",
            new_name="ContactInformation2",
        ),
    ]
