# Generated by Django 4.1.3 on 2023-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_teammember"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactInformation2",
            new_name="ContactInformation",
        ),
    ]
