# Generated by Django 4.1.3 on 2023-03-26 02:21

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_rename_contactinformation2_contactinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="address",
            field=api.customs.CustomTextField(
                help_text="Address", max_length=200, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="email",
            field=api.customs.CustomEmailField(
                help_text="Email Address", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="phone",
            field=api.customs.CustomCharField(
                help_text="Phone Number", max_length=20, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="friday",
            field=api.customs.CustomCharField(
                help_text="Friday", max_length=40, null=True, verbose_name="Friday"
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="monday",
            field=api.customs.CustomCharField(
                help_text="Monday", max_length=40, null=True, verbose_name="Monday"
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="saturday",
            field=api.customs.CustomCharField(
                help_text="Saturday", max_length=40, null=True, verbose_name="Saturday"
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="sunday",
            field=api.customs.CustomCharField(
                help_text="Sunday", max_length=40, null=True, verbose_name="Sunday"
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="thursday",
            field=api.customs.CustomCharField(
                help_text="Thursday", max_length=40, null=True, verbose_name="Thursday"
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="tuesday",
            field=api.customs.CustomCharField(
                help_text="Tuesday", max_length=40, null=True, verbose_name="Tuesday"
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="wednesday",
            field=api.customs.CustomCharField(
                help_text="Wednesday",
                max_length=40,
                null=True,
                verbose_name="Wednesday",
            ),
        ),
        migrations.AlterField(
            model_name="socials",
            name="facebook",
            field=api.customs.CustomCharField(
                help_text="Facebook", max_length=100, null=True, verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="socials",
            name="github",
            field=api.customs.CustomCharField(
                help_text="Github", max_length=100, null=True, verbose_name="Github"
            ),
        ),
        migrations.AlterField(
            model_name="socials",
            name="instagram",
            field=api.customs.CustomCharField(
                help_text="Instagram",
                max_length=100,
                null=True,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="socials",
            name="linkedin",
            field=api.customs.CustomCharField(
                help_text="LinkedIn", max_length=100, null=True, verbose_name="LinkedIn"
            ),
        ),
        migrations.AlterField(
            model_name="socials",
            name="twitter",
            field=api.customs.CustomCharField(
                help_text="Twitter", max_length=100, null=True, verbose_name="Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="socials",
            name="youtube",
            field=api.customs.CustomCharField(
                help_text="Youtube", max_length=100, null=True, verbose_name="Youtube"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio",
            field=api.customs.CustomTextField(
                help_text="Short Biography", max_length=500, verbose_name="Bio"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="facebook",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Facebook",
                max_length=100,
                null=True,
                verbose_name="Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="github",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="GitHub",
                max_length=100,
                null=True,
                verbose_name="GitHub",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.ImageField(
                help_text="Image", upload_to="about_members", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="instagram",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Instagram",
                max_length=100,
                null=True,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="linkedIn",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="LinkedIn",
                max_length=100,
                null=True,
                verbose_name="LinkedIn",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Full Name", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=api.customs.CustomCharField(
                help_text="Role", max_length=100, verbose_name="Role"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="twitter",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Twitter",
                max_length=100,
                null=True,
                verbose_name="Twitter",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="youtube",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="YouTube",
                max_length=100,
                null=True,
                verbose_name="YouTube",
            ),
        ),
    ]
