# Generated by Django 4.1.3 on 2023-03-30 01:56

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contactinformation_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        default="Placeholder",
                        help_text="Hero Name",
                        max_length=20,
                        verbose_name="Hero Name",
                    ),
                ),
                (
                    "contact_info",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.contactinformation",
                    ),
                ),
                (
                    "hours",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.hours",
                    ),
                ),
                (
                    "socials",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.socials",
                    ),
                ),
            ],
        ),
    ]
