# Generated by Django 4.1.3 on 2023-04-03 19:35

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="set_name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Contact Information Set Name",
                max_length=100,
                verbose_name="Contact Information Set Name",
            ),
        ),
        migrations.AddField(
            model_name="hours",
            name="set_name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Hours Set Name",
                max_length=100,
                verbose_name="Hours Set Name",
            ),
        ),
        migrations.AddField(
            model_name="socials",
            name="set_name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Social Set Name",
                max_length=100,
                verbose_name="Social Set Name",
            ),
        ),
    ]
