# Generated by Django 4.1.3 on 2023-04-03 19:38

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_alter_contact_options_contactinformation_set_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="set_name",
            field=api.customs.CustomCharField(
                help_text="Contact Information Set Name",
                max_length=100,
                unique=True,
                verbose_name="Contact Information Set Name",
            ),
        ),
        migrations.AlterField(
            model_name="hours",
            name="set_name",
            field=api.customs.CustomCharField(
                help_text="Hours Set Name",
                max_length=100,
                unique=True,
                verbose_name="Hours Set Name",
            ),
        ),
        migrations.AlterField(
            model_name="socials",
            name="set_name",
            field=api.customs.CustomCharField(
                help_text="Social Set Name",
                max_length=100,
                unique=True,
                verbose_name="Social Set Name",
            ),
        ),
    ]
