# Generated by Django 4.1.3 on 2023-04-04 04:09

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0008_alter_contactinformation_set_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Referential Name",
                max_length=20,
                verbose_name="Referential Name",
            ),
        ),
    ]
