# Generated by Django 4.1.3 on 2023-03-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.page",
                    ),
                ),
                ("content", models.TextField()),
            ],
            bases=("content.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.page",
                    ),
                ),
                ("subtitle", models.CharField(max_length=255)),
            ],
            bases=("content.page",),
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("paragraph", "Paragraph"),
                            ("list", "List"),
                            ("dictionary", "Dictionary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("paragraph", "Paragraph"),
                            ("list", "List"),
                            ("dictionary", "Dictionary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "style",
                    models.CharField(
                        choices=[("unordered", "Unordered"), ("ordered", "Ordered")],
                        max_length=10,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "List",
            },
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("paragraph", "Paragraph"),
                            ("list", "List"),
                            ("dictionary", "Dictionary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("h1", "H1"),
                            ("h2", "H2"),
                            ("h3", "H3"),
                            ("h4", "H4"),
                            ("h5", "H5"),
                            ("h6", "H6"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header",
            },
        ),
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("paragraph", "Paragraph"),
                            ("list", "List"),
                            ("dictionary", "Dictionary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dictionary",
            },
        ),
    ]
