# Generated by Django 4.1.3 on 2023-03-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Header",
            new_name="Head",
        ),
        migrations.AlterModelOptions(
            name="dictionary",
            options={
                "verbose_name": "Dictionary",
                "verbose_name_plural": "Dictionaries",
            },
        ),
        migrations.AlterModelOptions(
            name="head",
            options={"verbose_name": "Head", "verbose_name_plural": "Heads"},
        ),
        migrations.AlterModelOptions(
            name="list",
            options={"verbose_name": "List", "verbose_name_plural": "Lists"},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"verbose_name": "Section", "verbose_name_plural": "Sections"},
        ),
        migrations.AlterModelOptions(
            name="text",
            options={"verbose_name": "Text", "verbose_name_plural": "Text"},
        ),
    ]
