# Generated by Django 4.1.3 on 2023-02-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_missionstatement"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body1", models.CharField(max_length=1000)),
                ("body2", models.CharField(max_length=1000)),
                ("body3", models.CharField(max_length=1000)),
            ],
        ),
    ]
