# Generated by Django 4.1.3 on 2023-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_companyhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyhistory",
            name="body1",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="companyhistory",
            name="body2",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="companyhistory",
            name="body3",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="missionstatement",
            name="body1",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="missionstatement",
            name="body2",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="missionstatement",
            name="body3",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
