# Generated by Django 4.1.3 on 2023-02-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_alter_companyhistory_body1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=40)),
            ],
        ),
    ]
