# Generated by Django 4.1.3 on 2023-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_rename_body1_companyhistory_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="about_members")),
                ("bio", models.TextField()),
                ("linkedIn", models.URLField()),
                ("github", models.URLField()),
                ("twitter", models.URLField()),
                ("skills", models.ManyToManyField(to="about.skill")),
            ],
        ),
    ]
