# Generated by Django 4.1.3 on 2023-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0009_alter_teammember_github_alter_teammember_linkedin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("monday", models.CharField(max_length=40, null=True)),
                ("tuesday", models.CharField(max_length=40, null=True)),
                ("wednesday", models.CharField(max_length=40, null=True)),
                ("thursday", models.CharField(max_length=40, null=True)),
                ("friday", models.CharField(max_length=40, null=True)),
                ("saturday", models.CharField(max_length=40, null=True)),
                ("sunday", models.CharField(max_length=40, null=True)),
                ("facebook", models.CharField(max_length=100, null=True)),
                ("instagram", models.CharField(max_length=100, null=True)),
                ("linkedin", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
