# Generated by Django 4.1.3 on 2023-02-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0010_contactinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinformation",
            name="twitter",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
