# Generated by Django 4.1.3 on 2023-02-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0012_category_faq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="skills",
        ),
    ]
