# Generated by Django 4.1.3 on 2023-02-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0013_remove_teammember_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionstatement",
            name="body",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
