# Generated by Django 4.1.3 on 2023-02-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0014_alter_missionstatement_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyhistory",
            name="body",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
