# Generated by Django 4.1.3 on 2023-02-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0015_alter_companyhistory_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutblock",
            options={"verbose_name": "Heading", "verbose_name_plural": "Headings"},
        ),
        migrations.AlterModelOptions(
            name="companyhistory",
            options={"verbose_name": "History", "verbose_name_plural": "Historys"},
        ),
        migrations.AlterModelOptions(
            name="contactinformation",
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Informations",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQs"},
        ),
        migrations.AlterModelOptions(
            name="missionstatement",
            options={
                "verbose_name": "Mission Statement",
                "verbose_name_plural": "Mission Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={"verbose_name": "Members", "verbose_name_plural": "Members"},
        ),
        migrations.AlterModelOptions(
            name="value",
            options={"verbose_name": "Values", "verbose_name_plural": "Values"},
        ),
    ]
