# Generated by Django 4.1.3 on 2023-03-02 03:47

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0017_alter_aboutblock_image_alter_aboutblock_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "FAQ Categories",
                "verbose_name_plural": "FAQ CategoriesCategories",
            },
        ),
        migrations.AlterField(
            model_name="companyhistory",
            name="body",
            field=api.customs.CustomTextField(
                max_length=10000, null=True, verbose_name="Body"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=api.customs.CustomTextField(max_length=500, verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="about.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=api.customs.CustomTextField(max_length=500, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="missionstatement",
            name="body",
            field=api.customs.CustomTextField(
                max_length=10000, null=True, verbose_name="Body"
            ),
        ),
    ]
