# Generated by Django 4.1.3 on 2023-03-13 22:03

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0019_alter_contactinformation_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="facebook",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, null=True, verbose_name="Facebook"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="instagram",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="youtube",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, null=True, verbose_name="YouTube"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="github",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, null=True, verbose_name="GitHub"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="linkedIn",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, null=True, verbose_name="LinkedIn"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="twitter",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, null=True, verbose_name="Twitter"
            ),
        ),
    ]
