# Generated by Django 4.1.3 on 2023-03-13 22:13

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0020_teammember_facebook_teammember_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinformation",
            name="github",
            field=api.customs.CustomCharField(
                max_length=100, null=True, verbose_name="Github"
            ),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="youtube",
            field=api.customs.CustomCharField(
                max_length=100, null=True, verbose_name="Youtube"
            ),
        ),
    ]
