# Generated by Django 4.1.3 on 2023-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0022_alter_aboutblock_image_alter_aboutblock_title_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactInformation",
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
