# Generated by Django 4.1.3 on 2023-03-25 15:02

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0023_delete_contactinformation_delete_teammember"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AlterModelOptions(
            name="aboutblock",
            options={
                "verbose_name": "About Header",
                "verbose_name_plural": "About Headers",
            },
        ),
        migrations.AlterField(
            model_name="aboutblock",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Company Name", max_length=200, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Category Name", max_length=100, verbose_name="Category"
            ),
        ),
        migrations.AlterField(
            model_name="companyhistory",
            name="body",
            field=api.customs.CustomTextField(
                help_text="Company History Body",
                max_length=10000,
                null=True,
                verbose_name="Body",
            ),
        ),
        migrations.AlterField(
            model_name="companyhistory",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Section Title", max_length=200, verbose_name="Section Title"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=api.customs.CustomTextField(
                help_text="FAQ Answer", max_length=500, verbose_name="Answer"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                help_text="FAQ Category",
                on_delete=django.db.models.deletion.CASCADE,
                to="about.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=api.customs.CustomTextField(
                help_text="FAQ Question", max_length=500, verbose_name="Question"
            ),
        ),
        migrations.AlterField(
            model_name="missionstatement",
            name="body",
            field=api.customs.CustomTextField(
                help_text="Mission Statement Body",
                max_length=10000,
                null=True,
                verbose_name="Body",
            ),
        ),
        migrations.AlterField(
            model_name="missionstatement",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Section Title", max_length=200, verbose_name="Section Title"
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="icon",
            field=api.customs.CustomCharField(
                help_text="Value Icon", max_length=40, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Value Title", max_length=100, verbose_name="Title"
            ),
        ),
    ]
