# Generated by Django 4.1.3 on 2023-04-03 15:20

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_delete_skill_alter_aboutblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutblock',
            name='image',
            field=api.customs.CustomImageFieldField(upload_to='about'),
        ),
    ]
