# Generated by Django 4.1.3 on 2023-04-04 03:37

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0025_alter_aboutblock_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutblock",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Referential Name",
                max_length=100,
                verbose_name="About Block Name",
            ),
        ),
        migrations.AddField(
            model_name="companyhistory",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Referential Name",
                max_length=100,
                verbose_name="Company History Name",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Referential Name",
                max_length=100,
                verbose_name="FAQ Name",
            ),
        ),
        migrations.AddField(
            model_name="missionstatement",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Referential Name",
                max_length=100,
                verbose_name="Mission Statement Name",
            ),
        ),
        migrations.AddField(
            model_name="value",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Referential Name",
                max_length=100,
                verbose_name="Value Name",
            ),
        ),
    ]
