# Generated by Django 4.1.3 on 2023-04-04 03:57

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0027_alter_companyhistory_options_remove_value_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["category"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AlterField(
            model_name="faq",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="Referential Name",
                max_length=100,
                unique=True,
                verbose_name="FAQ Name",
            ),
        ),
    ]
