# Generated by Django 4.1.3 on 2023-02-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"verbose_name": "Messages", "verbose_name_plural": "Messages"},
        ),
    ]
