# Generated by Django 4.1.3 on 2023-03-04 22:17

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_messages_phone_alter_messages_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="phone",
            field=api.customs.CustomCharField(max_length=20, verbose_name="Phone"),
        ),
    ]
