# Generated by Django 4.1.3 on 2023-03-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "subscribed_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Subscribed On"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscribers",
                "verbose_name_plural": "Subscribers",
            },
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
