# Generated by Django 4.1.3 on 2023-03-14 20:08

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_subscribers_delete_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="message",
            field=api.customs.CustomTextField(max_length=20000, verbose_name="Message"),
        ),
    ]
