# Generated by Django 4.1.3 on 2023-03-25 15:02

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0008_alter_messages_email_alter_messages_is_archived_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="is_replied",
        ),
        migrations.AlterField(
            model_name="messages",
            name="email",
            field=api.customs.CustomEmailField(
                help_text="Email Address", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="is_archived",
            field=api.customs.CustomBooleanField(
                default=False,
                help_text="Is Archived Status",
                verbose_name="Is Archived",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="is_read",
            field=api.customs.CustomBooleanField(
                default=False, help_text="Is Read Status", verbose_name="Is Read"
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="message",
            field=api.customs.CustomTextField(
                help_text="Message Content", max_length=20000, verbose_name="Message"
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Full Name", max_length=50, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="phone",
            field=api.customs.CustomCharField(
                help_text="Phone Number", max_length=20, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="subject",
            field=api.customs.CustomCharField(
                help_text="Message Subject", max_length=100, verbose_name="Subject"
            ),
        ),
    ]
