# Generated by Django 4.1.3 on 2023-03-26 02:21

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0009_remove_messages_is_replied_alter_messages_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribers",
            name="email",
            field=api.customs.CustomEmailField(
                help_text="Email Address",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
