# Generated by Django 4.1.3 on 2023-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Position", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
