# Generated by Django 4.1.3 on 2023-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0002_delete_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=40)),
                ("location", models.CharField(max_length=80)),
                ("type", models.CharField(max_length=20)),
                ("who_we_are", models.TextField(max_length=500)),
                ("why_apply", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requirements",
                    models.ManyToManyField(
                        related_name="requirement", to="jobs.requirement"
                    ),
                ),
            ],
        ),
    ]
