# Generated by Django 4.1.3 on 2023-02-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsibilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="jobposting",
            name="responsibilities",
            field=models.ManyToManyField(
                related_name="responsibilities", to="jobs.responsibilities"
            ),
        ),
    ]
