# Generated by Django 4.1.3 on 2023-02-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_responsibilities_jobposting_responsibilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement",
            name="detail",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="responsibilities",
            name="detail",
            field=models.CharField(max_length=200),
        ),
    ]
