# Generated by Django 4.1.3 on 2023-02-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_requirement_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="looking_for",
            field=models.TextField(max_length=500, null=True),
        ),
    ]
