# Generated by Django 4.1.3 on 2023-02-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_jobposting_looking_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="tagline",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
