# Generated by Django 4.1.3 on 2023-02-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_jobposting_tagline"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="filled",
            field=models.BooleanField(default=False),
        ),
    ]
