# Generated by Django 4.1.3 on 2023-02-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobposting_filled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposting",
            options={"verbose_name": "Openings", "verbose_name_plural": "Openings"},
        ),
    ]
