# Generated by Django 4.1.3 on 2023-02-27 15:58

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_jobposting_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposting",
            options={
                "verbose_name": "Job Openings",
                "verbose_name_plural": "Job Openings",
            },
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="filled",
            field=models.BooleanField(default=False, verbose_name="Filled"),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=api.customs.CustomCharField(max_length=80, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="looking_for",
            field=models.TextField(
                max_length=500, null=True, verbose_name="Looking For"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="position",
            field=api.customs.CustomCharField(max_length=40, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="requirements",
            field=models.ManyToManyField(
                related_name="requirement",
                to="jobs.requirement",
                verbose_name="Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="responsibilities",
            field=models.ManyToManyField(
                related_name="responsibilities",
                to="jobs.responsibilities",
                verbose_name="Responsibilities",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="tagline",
            field=models.TextField(max_length=100, null=True, verbose_name="Tagline"),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="type",
            field=api.customs.CustomCharField(max_length=20, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="who_we_are",
            field=models.TextField(max_length=500, verbose_name="Who We Are"),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="why_apply",
            field=models.TextField(max_length=500, verbose_name="Why Apply"),
        ),
    ]
