# Generated by Django 4.1.3 on 2023-03-07 17:57

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_alter_jobposting_options_alter_jobposting_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    api.customs.CustomCharField(
                        max_length=30, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    api.customs.CustomCharField(
                        max_length=30, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    api.customs.CustomEmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    api.customs.CustomCharField(max_length=20, verbose_name="Phone"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "city",
                    api.customs.CustomCharField(max_length=40, verbose_name="City"),
                ),
                (
                    "zipcode",
                    api.customs.CustomCharField(max_length=15, verbose_name="Zip Code"),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
    ]
