# Generated by Django 4.1.3 on 2023-03-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="jobs.jobposting",
                verbose_name="Job",
            ),
        ),
    ]
