# Generated by Django 4.1.3 on 2023-03-07 18:11

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_application_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Supported file types: PDF, Microsoft Word, plain text.",
                null=True,
                upload_to="resumes/",
                verbose_name="Resume",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=api.customs.CustomCharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewing", "Reviewing"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
