# Generated by Django 4.1.3 on 2023-03-13 13:25

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="looking_for",
            field=api.customs.CustomTextField(
                max_length=500, null=True, verbose_name="Looking For"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="tagline",
            field=api.customs.CustomTextField(
                max_length=100, null=True, verbose_name="Tagline"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="who_we_are",
            field=api.customs.CustomTextField(
                max_length=500, verbose_name="Who We Are"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="why_apply",
            field=api.customs.CustomTextField(max_length=500, verbose_name="Why Apply"),
        ),
    ]
