# Generated by Django 4.1.3 on 2023-03-26 02:21

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_alter_application_city_alter_application_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="city",
            field=api.customs.CustomCharField(
                help_text="City", max_length=40, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="email",
            field=api.customs.CustomEmailField(
                help_text="Email Address", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="first_name",
            field=api.customs.CustomCharField(
                help_text="First Name", max_length=30, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                default=1,
                help_text="Related Job",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="jobs.jobposting",
                verbose_name="Job",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_name",
            field=api.customs.CustomCharField(
                help_text="Last Name", max_length=30, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone",
            field=api.customs.CustomCharField(
                help_text="Phone Number", max_length=20, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=api.customs.CustomCharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Reviewing", "Reviewing"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                ],
                default="Pending",
                help_text="Application Status",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="zipcode",
            field=api.customs.CustomCharField(
                help_text="Zip Code", max_length=15, verbose_name="Zip Code"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="filled",
            field=models.BooleanField(
                default=False, help_text="Filled Status", verbose_name="Filled"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=api.customs.CustomCharField(
                help_text="Job Location", max_length=80, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="looking_for",
            field=api.customs.CustomTextField(
                help_text="Looking For Text",
                max_length=500,
                null=True,
                verbose_name="Looking For",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="position",
            field=api.customs.CustomCharField(
                help_text="Job Title/Position", max_length=40, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="requirements",
            field=models.ManyToManyField(
                help_text="Job Requirements",
                related_name="requirement",
                to="jobs.requirement",
                verbose_name="Requirements",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="responsibilities",
            field=models.ManyToManyField(
                help_text="Job Responsibilities",
                related_name="responsibilities",
                to="jobs.responsibilities",
                verbose_name="Responsibilities",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="tagline",
            field=api.customs.CustomTextField(
                help_text="Job Post Tagline",
                max_length=100,
                null=True,
                verbose_name="Tagline",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="type",
            field=api.customs.CustomCharField(
                help_text="Employment Type", max_length=20, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="who_we_are",
            field=api.customs.CustomTextField(
                help_text="Who We Are Text", max_length=500, verbose_name="Who We Are"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="why_apply",
            field=api.customs.CustomTextField(
                help_text="Why Apply Text", max_length=500, verbose_name="Why Apply"
            ),
        ),
    ]
