# Generated by Django 4.1.3 on 2023-02-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_tile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="carousel")),
                ("buttonText", models.CharField(max_length=20)),
                ("buttonLink", models.CharField(max_length=20)),
            ],
        ),
    ]
