# Generated by Django 4.1.3 on 2023-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("center", "Center"),
                        ],
                        max_length=10,
                    ),
                ),
                ("show_divider", models.BooleanField(default=False)),
            ],
        ),
    ]
