# Generated by Django 4.1.3 on 2023-02-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0004_titleblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="titleblock",
            name="name",
            field=models.CharField(default="default", max_length=100, unique=True),
        ),
    ]
