# Generated by Django 4.1.3 on 2023-02-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0005_titleblock_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="testimonial_images")),
                ("name", models.CharField(max_length=40)),
                ("position", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
