# Generated by Django 4.1.3 on 2023-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0007_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="titleblock",
            name="description",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
