# Generated by Django 4.1.3 on 2023-02-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0008_titleblock_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleblock",
            name="alignment",
            field=models.CharField(
                choices=[("Left", "Left"), ("Right", "Right"), ("Center", "Center")],
                max_length=10,
            ),
        ),
    ]
