# Generated by Django 4.1.3 on 2023-02-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0009_alter_titleblock_alignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={"verbose_name": "Feature", "verbose_name_plural": "Features"},
        ),
        migrations.AlterModelOptions(
            name="heroblock",
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AlterModelOptions(
            name="pricingplan",
            options={
                "verbose_name": "Pricing Tiers",
                "verbose_name_plural": "Pricing Tiers",
            },
        ),
        migrations.AlterModelOptions(
            name="process",
            options={"verbose_name": "Processes", "verbose_name_plural": "Processes"},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "verbose_name": "Testimonials",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AlterModelOptions(
            name="titleblock",
            options={
                "verbose_name": "Heading Blocks",
                "verbose_name_plural": "Heading Blocks",
            },
        ),
        migrations.RenameField(
            model_name="pricingplan",
            old_name="features",
            new_name="feature",
        ),
        migrations.RenameField(
            model_name="pricingplan",
            old_name="supportedsites",
            new_name="supported_sites",
        ),
    ]
