# Generated by Django 4.1.3 on 2023-02-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0011_rename_feature_pricingplan_features"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tile",
        ),
        migrations.AlterModelOptions(
            name="supportedsites",
            options={
                "verbose_name": "SupportedSites",
                "verbose_name_plural": "SupportedSites",
            },
        ),
    ]
