# Generated by Django 4.1.3 on 2023-02-27 16:21

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0013_alter_titleblock_options_alter_feature_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportedsites",
            name="site",
        ),
        migrations.AddField(
            model_name="supportedsites",
            name="detail",
            field=api.customs.CustomCharField(default="www.google.com", max_length=100),
        ),
    ]
