# Generated by Django 4.1.3 on 2023-02-27 16:23

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0014_remove_supportedsites_site_supportedsites_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportedsites",
            name="detail",
            field=api.customs.CustomCharField(max_length=100),
        ),
    ]
