# Generated by Django 4.1.3 on 2023-02-27 21:51

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0015_alter_supportedsites_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplan",
            name="features",
            field=api.customs.CustomManyToManyField(
                related_name="features", to="landing.feature", verbose_name="Features"
            ),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="image",
            field=models.ImageField(upload_to="pricing_images", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="supported_sites",
            field=api.customs.CustomManyToManyField(
                related_name="supportedsites",
                to="landing.supportedsites",
                verbose_name="Supported Sites",
            ),
        ),
    ]
