# Generated by Django 4.1.3 on 2023-02-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0016_alter_pricingplan_features_alter_pricingplan_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplan",
            name="features",
            field=models.ManyToManyField(
                related_name="features", to="landing.feature", verbose_name="Features"
            ),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="supported_sites",
            field=models.ManyToManyField(
                related_name="supportedsites",
                to="landing.supportedsites",
                verbose_name="Supported Sites",
            ),
        ),
    ]
