# Generated by Django 4.1.3 on 2023-03-06 15:37

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0019_rename_title_pricingplan_service_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_title",
                    api.customs.CustomCharField(
                        max_length=100, verbose_name="Service Title"
                    ),
                ),
                (
                    "price",
                    api.customs.CustomDecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="pricing_images", verbose_name="Image"),
                ),
                (
                    "paragraph_one",
                    api.customs.CustomTextField(
                        max_length=500, verbose_name="Paragraph 1"
                    ),
                ),
                (
                    "paragraph_two",
                    api.customs.CustomTextField(
                        max_length=500, verbose_name="Paragraph 2"
                    ),
                ),
                (
                    "paragraph_three",
                    api.customs.CustomTextField(
                        max_length=500, verbose_name="Paragraph 3"
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="features",
                        to="landing.feature",
                        verbose_name="Features",
                    ),
                ),
                (
                    "supported_sites",
                    models.ManyToManyField(
                        related_name="supportedsites",
                        to="landing.supportedsites",
                        verbose_name="Supported Sites",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Tiers",
                "verbose_name_plural": "Pricing Tiers",
            },
        ),
        migrations.DeleteModel(
            name="PricingPlan",
        ),
    ]
