# Generated by Django 4.1.3 on 2023-03-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0020_servicetier_delete_pricingplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetier",
            name="image_two",
            field=models.ImageField(
                default="", upload_to="pricing_images", verbose_name="Image #2"
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="image",
            field=models.ImageField(
                upload_to="pricing_images", verbose_name="Image #1"
            ),
        ),
    ]
