# Generated by Django 4.1.3 on 2023-03-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0021_servicetier_image_two_alter_servicetier_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicetier",
            name="image_two",
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="image",
            field=models.ImageField(upload_to="pricing_images", verbose_name="Image"),
        ),
    ]
