# Generated by Django 4.1.3 on 2023-03-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0022_remove_servicetier_image_two_alter_servicetier_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetier",
            options={
                "verbose_name": "Service Tiers",
                "verbose_name_plural": "Service Tiers",
            },
        ),
    ]
