# Generated by Django 4.1.3 on 2023-03-19 19:32

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0025_alter_supportedsites_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="detail",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder",
                max_length=100,
                verbose_name="Feature Detail",
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="buttonText",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder",
                max_length=50,
                verbose_name="Button Text",
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="heading",
            field=api.customs.CustomTextField(
                help_text="Help Text Placeholder",
                max_length=500,
                verbose_name="Tagline",
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="text",
            field=api.customs.CustomTextField(
                help_text="Help Text Placeholder",
                max_length=500,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder", max_length=200, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Help Text Placeholder",
                max_length=200,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="icon",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder", max_length=40, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder", max_length=100, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="features",
            field=api.customs.CustomManyToManyField(
                help_text="Help Text Placeholder",
                related_name="features",
                to="landing.feature",
                verbose_name="Features",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="image",
            field=models.ImageField(
                help_text="Help Text Placeholder",
                upload_to="pricing_images",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="paragraph_one",
            field=api.customs.CustomTextField(
                help_text="Help Text Placeholder",
                max_length=500,
                verbose_name="Paragraph 1",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="paragraph_three",
            field=api.customs.CustomTextField(
                help_text="Help Text Placeholder",
                max_length=500,
                verbose_name="Paragraph 3",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="paragraph_two",
            field=api.customs.CustomTextField(
                help_text="Help Text Placeholder",
                max_length=500,
                verbose_name="Paragraph 2",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="price",
            field=api.customs.CustomDecimalField(
                decimal_places=2,
                help_text="Help Text Placeholder",
                max_digits=10,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="service_title",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder",
                max_length=100,
                verbose_name="Service Title",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="supported_sites",
            field=api.customs.CustomManyToManyField(
                help_text="Help Text Placeholder",
                related_name="supportedsites",
                to="landing.supportedsites",
                verbose_name="Supported Sites",
            ),
        ),
        migrations.AlterField(
            model_name="supportedsites",
            name="detail",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder",
                max_length=100,
                verbose_name="Supported Site Detail",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Help Text Placeholder",
                max_length=250,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder",
                max_length=100,
                unique=True,
                verbose_name="Section Name",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="show_divider",
            field=models.BooleanField(
                default=False,
                help_text="Help Text Placeholder",
                verbose_name="Show Divider?",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="subtitle",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder",
                max_length=100,
                verbose_name="Subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder", max_length=100, verbose_name="Title"
            ),
        ),
    ]
