# Generated by Django 4.1.3 on 2023-03-25 15:02

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0026_alter_feature_detail_alter_heroblock_buttontext_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="detail",
            field=api.customs.CustomCharField(
                help_text="Feature Detail",
                max_length=100,
                verbose_name="Feature Detail",
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="buttonText",
            field=api.customs.CustomCharField(
                help_text="Button Text", max_length=50, verbose_name="Button Text"
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="heading",
            field=api.customs.CustomTextField(
                help_text="Subheader", max_length=500, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="text",
            field=api.customs.CustomTextField(
                help_text="Description", max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="heroblock",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Header", max_length=200, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Description", max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="icon",
            field=api.customs.CustomCharField(
                help_text="Select Icon", max_length=40, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Header", max_length=100, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="features",
            field=api.customs.CustomManyToManyField(
                help_text="Service Tier Features",
                related_name="features",
                to="landing.feature",
                verbose_name="Features",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="image",
            field=models.ImageField(
                help_text="Image", upload_to="pricing_images", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="paragraph_one",
            field=api.customs.CustomTextField(
                help_text="Paragraph One", max_length=500, verbose_name="Paragraph One"
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="paragraph_three",
            field=api.customs.CustomTextField(
                help_text="Paragraph Three",
                max_length=500,
                verbose_name="Paragraph Three",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="paragraph_two",
            field=api.customs.CustomTextField(
                help_text="Paragraph Two", max_length=500, verbose_name="Paragraph Two"
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="price",
            field=api.customs.CustomDecimalField(
                decimal_places=2,
                help_text="Service Tier Price",
                max_digits=10,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="service_title",
            field=api.customs.CustomCharField(
                help_text="Service Tier Title",
                max_length=100,
                verbose_name="Service Title",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="supported_sites",
            field=api.customs.CustomManyToManyField(
                help_text="Service Tier Supported Sites",
                related_name="supportedsites",
                to="landing.supportedsites",
                verbose_name="Supported Sites",
            ),
        ),
        migrations.AlterField(
            model_name="supportedsites",
            name="detail",
            field=api.customs.CustomCharField(
                help_text="Supported Site Detail",
                max_length=100,
                verbose_name="Supported Site Detail",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="alignment",
            field=api.customs.CustomCharField(
                choices=[("Left", "Left"), ("Right", "Right"), ("Center", "Center")],
                help_text="Description Text",
                max_length=10,
                verbose_name="Text Alignment",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Description Text",
                max_length=250,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Referential Name",
                max_length=100,
                unique=True,
                verbose_name="Section Name",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="show_divider",
            field=models.BooleanField(
                default=False,
                help_text="Optional Divider Below Section Header",
                verbose_name="Bottom Divider",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="subtitle",
            field=api.customs.CustomCharField(
                help_text="Subheader Text", max_length=100, verbose_name="Subheader"
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Header Text", max_length=100, verbose_name="Header"
            ),
        ),
    ]
