# Generated by Django 4.1.3 on 2023-03-28 18:26

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0029_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Hero Name",
                max_length=20,
                null=True,
                verbose_name="Hero Name",
            ),
        ),
    ]
