# Generated by Django 4.1.3 on 2023-03-28 18:30

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0030_hero_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Hero Name",
                max_length=20,
                verbose_name="Hero Name",
            ),
        ),
    ]
