# Generated by Django 4.1.3 on 2023-03-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contactinformation_address_and_more"),
        ("landing", "0032_processes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="hero",
            name="socials",
        ),
        migrations.AddField(
            model_name="hero",
            name="contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.contactinformation",
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="social",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.socials",
            ),
        ),
    ]
