# Generated by Django 4.1.3 on 2023-03-28 22:38

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_alter_articles_tags"),
        ("landing", "0033_remove_hero_contacts_remove_hero_socials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="hero_block",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="landing.heroblock",
            ),
        ),
        migrations.CreateModel(
            name="LatestNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        default="Placeholder",
                        help_text="Hero Name",
                        max_length=20,
                        verbose_name="Hero Name",
                    ),
                ),
                ("latest_articles", models.ManyToManyField(to="articles.articles")),
                (
                    "title_block",
                    models.ForeignKey(
                        limit_choices_to={"name": "news"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.titleblock",
                    ),
                ),
            ],
        ),
    ]
