# Generated by Django 4.1.3 on 2023-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_alter_articles_managers"),
        ("landing", "0034_alter_hero_hero_block_latestnews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestnews",
            name="latest_articles",
            field=models.ManyToManyField(
                related_name="latest_articles_highlighted", to="articles.articles"
            ),
        ),
    ]
