# Generated by Django 4.1.3 on 2023-04-04 03:36

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0008_alter_contactinformation_set_name_and_more"),
        ("landing", "0035_alter_latestnews_latest_articles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hero",
            options={"verbose_name": "Hero", "verbose_name_plural": "Heros"},
        ),
        migrations.AlterModelOptions(
            name="latestnews",
            options={
                "verbose_name": "Latest News",
                "verbose_name_plural": "Latest News",
            },
        ),
        migrations.AlterModelOptions(
            name="processes",
            options={"verbose_name": "Processes", "verbose_name_plural": "Processes"},
        ),
        migrations.AlterField(
            model_name="hero",
            name="contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.contactinformation",
                verbose_name="Contact Information",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="hero_block",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="landing.heroblock",
                verbose_name="Attached Hero Block Data",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="social",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.socials",
                verbose_name="Socials",
            ),
        ),
        migrations.AlterField(
            model_name="latestnews",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Latest News Slug",
                max_length=20,
                verbose_name="Latest News Slug",
            ),
        ),
    ]
