# Generated by Django 4.1.3 on 2023-04-04 04:09

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0036_alter_hero_options_alter_latestnews_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hero",
            options={
                "ordering": ["name"],
                "verbose_name": "Hero",
                "verbose_name_plural": "Heros",
            },
        ),
        migrations.AlterModelOptions(
            name="heroblock",
            options={
                "ordering": ["name"],
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="latestnews",
            options={
                "ordering": ["name"],
                "verbose_name": "Latest News",
                "verbose_name_plural": "Latest News",
            },
        ),
        migrations.AlterModelOptions(
            name="process",
            options={
                "ordering": ["title"],
                "verbose_name": "Processes",
                "verbose_name_plural": "Processes",
            },
        ),
        migrations.AlterModelOptions(
            name="processes",
            options={
                "ordering": ["name"],
                "verbose_name": "Processes",
                "verbose_name_plural": "Processes",
            },
        ),
        migrations.AlterModelOptions(
            name="servicetier",
            options={
                "ordering": ["service_title"],
                "verbose_name": "Service Tiers",
                "verbose_name_plural": "Service Tiers",
            },
        ),
        migrations.AlterModelOptions(
            name="titleblock",
            options={
                "ordering": ["name"],
                "verbose_name": "Section Headings",
                "verbose_name_plural": "Section Headings",
            },
        ),
        migrations.AddField(
            model_name="heroblock",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Referential Name",
                max_length=100,
                verbose_name="Hero Block Name",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Hero Name",
                max_length=20,
                verbose_name="Hero Name",
            ),
        ),
        migrations.AlterField(
            model_name="processes",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Hero Name",
                max_length=20,
                verbose_name="Hero Name",
            ),
        ),
        migrations.AlterField(
            model_name="servicetier",
            name="service_title",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="Service Tier Title",
                max_length=100,
                verbose_name="Service Title",
            ),
        ),
        migrations.AlterField(
            model_name="titleblock",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="Referential Name",
                max_length=100,
                unique=True,
                verbose_name="Section Name",
            ),
        ),
    ]
