# Generated by Django 4.1.3 on 2023-04-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0038_delete_testimonial_alter_heroblock_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
