# Generated by Django 4.1.3 on 2023-04-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0009_alter_contact_name"),
        ("articles", "0012_alter_articles_managers"),
        ("landing", "0040_alter_heroblock_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="process",
            options={
                "ordering": ["title"],
                "verbose_name": "Process Item",
                "verbose_name_plural": "Process Items",
            },
        ),
        migrations.AlterModelOptions(
            name="processes",
            options={
                "ordering": ["name"],
                "verbose_name": "Process Component Set",
                "verbose_name_plural": "Process Component Sets",
            },
        ),
        migrations.AlterField(
            model_name="hero",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.contactinformation",
                verbose_name="Contact Information",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="hero_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="landing.heroblock",
                verbose_name="Attached Hero Block Data",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="social",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.socials",
                verbose_name="Socials",
            ),
        ),
        migrations.AlterField(
            model_name="latestnews",
            name="latest_articles",
            field=models.ManyToManyField(
                related_name="latest_articles_highlighted_objects",
                to="articles.articles",
            ),
        ),
    ]
