# Generated by Django 4.1.3 on 2023-03-26 02:21

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_contenttextblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttextblock",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Description", max_length=300, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="contenttextblock",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Header", max_length=200, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="description",
            field=api.customs.CustomTextField(
                help_text="SEO Description", max_length=300, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="keywords",
            field=api.customs.CustomTextField(
                help_text="SEO Keywords", max_length=200, verbose_name="Keywords"
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="page",
            field=api.customs.CustomCharField(
                help_text="Referential Page", max_length=20, verbose_name="Page"
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="title",
            field=api.customs.CustomTextField(
                help_text="SEO Title", max_length=200, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="url",
            field=api.customs.CustomURLField(help_text="SEO URL", verbose_name="URL"),
        ),
    ]
