from django.urls import path
from .views import *


urlpatterns = [
    path(
        "cardelement/",
        CardElementAPIView.as_view(),
        name="cardelement-list",
    ),
    path(
        "cardelement/<int:pk>/",
        CardElementDetailAPIView.as_view(),
        name="cardelement_detail",
    ),
    path(
        "cardelement/bulk/",
        CardElementBulkAPIView.as_view(),
        name="cardelement-bulk-detail",
    ),
    path(
        "textelement/",
        TextElementAPIView.as_view(),
        name="textelement-list",
    ),
    path(
        "textelement/<int:pk>/",
        TextElementDetailAPIView.as_view(),
        name="textelement_detail",
    ),
    path(
        "textelement/bulk/",
        TextElementBulkAPIView.as_view(),
        name="textelement-bulk-detail",
    ),
    path(
        "listitemtag/",
        ListItemTagAPIView.as_view(),
        name="listitemtag-list",
    ),
    path(
        "listitemtag/<int:pk>/",
        ListItemTagDetailAPIView.as_view(),
        name="listitemtag_detail",
    ),
    path(
        "listitemtag/bulk/",
        ListItemTagBulkAPIView.as_view(),
        name="listitemtag-bulk-detail",
    ),
    path(
        "listelement/",
        ListElementAPIView.as_view(),
        name="listelement-list",
    ),
    path(
        "listelement/<int:pk>/",
        ListElementDetailAPIView.as_view(),
        name="listelement_detail",
    ),
    path(
        "listelement/bulk/",
        ListElementBulkAPIView.as_view(),
        name="listelement-bulk-detail",
    ),
    path(
        "listelementitem/",
        ListElementItemAPIView.as_view(),
        name="listelementitem-list",
    ),
    path(
        "listelementitem/<int:pk>/",
        ListElementItemDetailAPIView.as_view(),
        name="listelementitem_detail",
    ),
    path(
        "listelementitem/bulk/",
        ListElementItemBulkAPIView.as_view(),
        name="listelementitem-bulk-detail",
    ),
    path(
        "list-builder/",
        ListBuilder.as_view(),
        name="list-builder",
    ),
    path(
        "imagetag/",
        ImageTagAPIView.as_view(),
        name="imagetag-list",
    ),
    path(
        "imagetag/<int:pk>/",
        ImageTagDetailAPIView.as_view(),
        name="imagetag_detail",
    ),
    path(
        "imagetag/bulk/",
        ImageTagBulkAPIView.as_view(),
        name="imagetag-bulk-detail",
    ),
    path(
        "imageelement/",
        ImageElementAPIView.as_view(),
        name="imageelement-list",
    ),
    path(
        "imageelement/<int:pk>/",
        ImageElementDetailAPIView.as_view(),
        name="imageelement_detail",
    ),
    path(
        "imageelement/bulk/",
        ImageElementBulkAPIView.as_view(),
        name="imageelement-bulk-detail",
    ),
    path(
        "headerelement/",
        HeaderElementAPIView.as_view(),
        name="headerelement-list",
    ),
    path(
        "headerelement/<int:pk>/",
        HeaderElementDetailAPIView.as_view(),
        name="headerelement_detail",
    ),
    path(
        "headerelement/bulk/",
        HeaderElementBulkAPIView.as_view(),
        name="headerelement-bulk-detail",
    ),
    path(
        "elementset/",
        ElementSetAPIView.as_view(),
        name="elementset-list",
    ),
    path(
        "elementset/<int:pk>/",
        ElementSetDetailAPIView.as_view(),
        name="elementset_detail",
    ),
    path(
        "elementset/bulk/",
        ElementSetBulkAPIView.as_view(),
        name="elementset-bulk-detail",
    ),
    path(
        "element/",
        ElementAPIView.as_view(),
        name="element-list",
    ),
    path(
        "element/<int:pk>/",
        ElementDetailAPIView.as_view(),
        name="element_detail",
    ),
    path(
        "element/bulk/",
        ElementBulkAPIView.as_view(),
        name="element-bulk-detail",
    ),
    path(
        "elementsetcategory/",
        ElementSetCategoryAPIView.as_view(),
        name="elementsetcategory-list",
    ),
    path(
        "elementsetcategory/<int:pk>/",
        ElementSetCategoryDetailAPIView.as_view(),
        name="elementsetcategory-detail",
    ),
    path(
        "elementsetcategory/bulk/",
        ElementSetCategoryBulkAPIView.as_view(),
        name="elementsetcategory-bulk-detail",
    ),
    path("updated_lists/", update_list_elements, name="updated-lists"),
    # path(
    #     "delete_lists/",
    #     delete_list_elements_with_no_content_object,
    #     name="delete-lists",
    # ),
]
