from django.urls import path
from .views import *


urlpatterns = [
    path(
        "textelement/",
        TextElementAPIView.as_view(),
        name="textelement-list",
    ),
    path(
        "textelement/<int:pk>/",
        TextElementDetailAPIView.as_view(),
        name="textelement_detail",
    ),
    path(
        "textelement/bulk/",
        TextElementBulkAPIView.as_view(),
        name="textelement-bulk-detail",
    ),
    path(
        "imageelement/",
        ImageElementAPIView.as_view(),
        name="imageelement-list",
    ),
    path(
        "imageelement/<int:pk>/",
        ImageElementDetailAPIView.as_view(),
        name="imageelement_detail",
    ),
    path(
        "imageelement/bulk/",
        ImageElementBulkAPIView.as_view(),
        name="imageelement-bulk-detail",
    ),
    path(
        "headerelement/",
        HeaderElementAPIView.as_view(),
        name="headerelement-list",
    ),
    path(
        "headerelement/<int:pk>/",
        HeaderElementDetailAPIView.as_view(),
        name="headerelement_detail",
    ),
    path(
        "headerelement/bulk/",
        HeaderElementBulkAPIView.as_view(),
        name="headerelement-bulk-detail",
    ),
    path(
        "elementset/",
        ElementSetAPIView.as_view(),
        name="elementset-list",
    ),
    path(
        "elementset/<int:pk>/",
        ElementSetDetailAPIView.as_view(),
        name="elementset_detail",
    ),
    path(
        "elementset/bulk/",
        ElementSetBulkAPIView.as_view(),
        name="elementset-bulk-detail",
    ),
    path(
        "element/",
        ElementAPIView.as_view(),
        name="element-list",
    ),
    path(
        "element/<int:pk>/",
        ElementDetailAPIView.as_view(),
        name="element_detail",
    ),
    path(
        "element/bulk/",
        ElementBulkAPIView.as_view(),
        name="element-bulk-detail",
    ),
    path(
        "elementsetcategory/",
        ElementSetCategoryAPIView.as_view(),
        name="elementsetcategory-list",
    ),
    path(
        "elementsetcategory/<int:pk>/",
        ElementSetCategoryDetailAPIView.as_view(),
        name="elementsetcategory-detail",
    ),
    path(
        "elementsetcategory/bulk/",
        ElementSetCategoryBulkAPIView.as_view(),
        name="elementsetcategory-bulk-detail",
    ),
]
