# Generated by Django 4.1.3 on 2023-03-20 02:09

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCompareRows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    api.customs.CustomCharField(
                        default="Service Tiers",
                        max_length=40,
                        verbose_name="Table Name",
                    ),
                ),
                (
                    "feature",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=40,
                        verbose_name="Feature",
                    ),
                ),
                (
                    "tier1_value",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        verbose_name="Tier 1",
                    ),
                ),
                (
                    "tier2_value",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        verbose_name="Tier 2",
                    ),
                ),
                (
                    "tier3_value",
                    api.customs.CustomCharField(
                        help_text="Help Text Placeholder",
                        max_length=100,
                        verbose_name="Tier 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Table Rows",
                "verbose_name_plural": "Service Table Rows",
            },
        ),
        migrations.CreateModel(
            name="ServiceTableLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        default="Test", max_length=40, verbose_name="Set Name"
                    ),
                ),
                (
                    "service_tier1",
                    api.customs.CustomCharField(max_length=40, verbose_name="Tier 1"),
                ),
                (
                    "tier1_icon",
                    api.customs.CustomCharField(max_length=40, verbose_name="Icon 1"),
                ),
                (
                    "service_tier2",
                    api.customs.CustomCharField(max_length=40, verbose_name="Tier 2"),
                ),
                (
                    "tier2_icon",
                    api.customs.CustomCharField(max_length=40, verbose_name="Icon 2"),
                ),
                (
                    "service_tier3",
                    api.customs.CustomCharField(max_length=40, verbose_name="Tier 3"),
                ),
                (
                    "tier3_icon",
                    api.customs.CustomCharField(max_length=40, verbose_name="Icon 3"),
                ),
            ],
            options={
                "verbose_name": "Service Table Labels",
                "verbose_name_plural": "Service Table Labels",
            },
        ),
        migrations.CreateModel(
            name="ServiceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        help_text="Top Header Display of Hero Section",
                        max_length=20,
                        verbose_name="Table Name",
                    ),
                ),
                (
                    "labels",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_table",
                        to="tables.servicetablelabels",
                        verbose_name="Table Labels",
                    ),
                ),
                (
                    "rows",
                    models.ManyToManyField(
                        related_name="service_tables",
                        to="tables.servicecomparerows",
                        verbose_name="Table Rows",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Table",
                "verbose_name_plural": "Service Tables",
            },
        ),
    ]
