# Generated by Django 4.1.3 on 2023-03-25 15:02

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecomparerows",
            name="feature",
            field=api.customs.CustomCharField(
                help_text="Row Feature", max_length=40, verbose_name="Feature"
            ),
        ),
        migrations.AlterField(
            model_name="servicecomparerows",
            name="table_name",
            field=api.customs.CustomCharField(
                default="Service Tiers",
                help_text="Table Name Connection",
                max_length=40,
                verbose_name="Table Name",
            ),
        ),
        migrations.AlterField(
            model_name="servicecomparerows",
            name="tier1_value",
            field=api.customs.CustomCharField(
                help_text="Cell 1 Value", max_length=100, verbose_name="Tier 1"
            ),
        ),
        migrations.AlterField(
            model_name="servicecomparerows",
            name="tier2_value",
            field=api.customs.CustomCharField(
                help_text="Cell 2 Value", max_length=100, verbose_name="Tier 2"
            ),
        ),
        migrations.AlterField(
            model_name="servicecomparerows",
            name="tier3_value",
            field=api.customs.CustomCharField(
                help_text="Cell 3 Value", max_length=100, verbose_name="Tier 3"
            ),
        ),
        migrations.AlterField(
            model_name="servicetable",
            name="labels",
            field=models.OneToOneField(
                help_text="Table Name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_table",
                to="tables.servicetablelabels",
                verbose_name="Table Labels",
            ),
        ),
        migrations.AlterField(
            model_name="servicetable",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Table Name", max_length=20, verbose_name="Table Name"
            ),
        ),
        migrations.AlterField(
            model_name="servicetable",
            name="rows",
            field=models.ManyToManyField(
                help_text="Table Rows",
                related_name="service_tables",
                to="tables.servicecomparerows",
                verbose_name="Table Rows",
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="name",
            field=api.customs.CustomCharField(
                default="Test",
                help_text="Referential Name",
                max_length=40,
                verbose_name="Set Name",
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier1",
            field=api.customs.CustomCharField(
                help_text="Column One Name", max_length=40, verbose_name="Tier 1"
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier2",
            field=api.customs.CustomCharField(
                help_text="Column Two Name", max_length=40, verbose_name="Tier 2"
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier3",
            field=api.customs.CustomCharField(
                help_text="Column Three Name", max_length=40, verbose_name="Tier 3"
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="tier1_icon",
            field=api.customs.CustomCharField(
                help_text="Column One Icon", max_length=40, verbose_name="Icon 1"
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="tier2_icon",
            field=api.customs.CustomCharField(
                help_text="Column Two Icon", max_length=40, verbose_name="Icon 2"
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="tier3_icon",
            field=api.customs.CustomCharField(
                help_text="Column Three Icon", max_length=40, verbose_name="Icon 3"
            ),
        ),
    ]
