# Generated by Django 4.1.3 on 2023-03-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0003_rename_feature_servicecomparerows_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetable",
            name="labels",
            field=models.ForeignKey(
                help_text="Table Name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_table",
                to="tables.servicetablelabels",
                verbose_name="Table Labels",
            ),
        ),
    ]
