# Generated by Django 4.1.3 on 2023-04-04 21:50

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0006_alter_servicetable_labels_alter_servicetable_rows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecomparerows",
            options={
                "ordering": ["table_name", "detail"],
                "verbose_name": "Service Table Rows",
                "verbose_name_plural": "Service Table Rows",
            },
        ),
        migrations.AlterModelOptions(
            name="servicetable",
            options={
                "ordering": ["name"],
                "verbose_name": "Service Table",
                "verbose_name_plural": "Service Tables",
            },
        ),
        migrations.AlterModelOptions(
            name="servicetablelabels",
            options={
                "ordering": ["name"],
                "verbose_name": "Service Table Labels",
                "verbose_name_plural": "Service Table Labels",
            },
        ),
        migrations.AlterField(
            model_name="servicecomparerows",
            name="table_name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Service Tiers",
                help_text="Table Name Connection",
                max_length=40,
                verbose_name="Table Name",
            ),
        ),
        migrations.AlterField(
            model_name="servicetable",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="Table Name",
                max_length=20,
                verbose_name="Table Name",
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Test",
                help_text="Referential Name",
                max_length=40,
                verbose_name="Set Name",
            ),
        ),
    ]
