# Generated by Django 4.1.3 on 2023-04-07 00:24

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0008_table_row_column_cell"),
    ]

    operations = [
        migrations.AddField(
            model_name="row",
            name="name",
            field=api.customs.CustomCharField(
                blank=True,
                db_index=True,
                help_text="Column Name",
                max_length=50,
                null=True,
                verbose_name="Column Name",
            ),
        ),
    ]
