# Generated by Django 4.1.3 on 2023-02-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefit",
            name="description",
            field=models.CharField(max_length=250),
        ),
    ]
