# Generated by Django 4.1.3 on 2023-02-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_benefit_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Benefit",
            new_name="Benefits",
        ),
    ]
