# Generated by Django 4.1.3 on 2023-02-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_rename_benefit_benefits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefits",
            options={"verbose_name": "Benefits", "verbose_name_plural": "Benefits"},
        ),
    ]
