# Generated by Django 4.1.3 on 2023-02-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_benefits_created_at_benefits_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefits",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="benefits",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
