# Generated by Django 4.1.3 on 2023-02-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_benefits_created_at_alter_benefits_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benefits",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="benefits",
            name="updated_at",
        ),
    ]
