# Generated by Django 4.1.3 on 2023-03-06 20:12

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_remove_benefits_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessTextItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    api.customs.CustomCharField(max_length=100, verbose_name="Title"),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        max_length=500, verbose_name="Description"
                    ),
                ),
                (
                    "icon",
                    api.customs.CustomCharField(max_length=40, verbose_name="Icon"),
                ),
            ],
            options={
                "verbose_name": "Process Text Item",
                "verbose_name_plural": "Process Text Items",
            },
        ),
        migrations.CreateModel(
            name="ProcessText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(max_length=100, verbose_name="Name"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="process_images",
                        verbose_name="Image",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="items", to="services.processtextitem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Text",
                "verbose_name_plural": "Process Text",
            },
        ),
    ]
