# Generated by Django 4.1.3 on 2023-03-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_processtextitem_processtext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processtext",
            name="image",
        ),
        migrations.RemoveField(
            model_name="processtext",
            name="name",
        ),
    ]
