# Generated by Django 4.1.3 on 2023-03-07 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_remove_processtext_image_remove_processtext_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessText",
        ),
    ]
