# Generated by Django 4.1.3 on 2023-03-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_delete_processtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="process_images", verbose_name="Image"),
                ),
            ],
            options={
                "verbose_name": "Process Image Item",
                "verbose_name_plural": "Process Image Items",
            },
        ),
    ]
