# Generated by Django 4.1.3 on 2023-03-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0023_alter_servicetier_options"),
        ("services", "0014_remove_processimageitem_service_tier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processimageitem",
            name="servicetier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicetier",
                to="landing.servicetier",
                verbose_name="Service Tier",
            ),
        ),
        migrations.CreateModel(
            name="ServiceTableLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier1_icon", models.CharField(max_length=50)),
                ("tier2_icon", models.CharField(max_length=50)),
                ("tier3_icon", models.CharField(max_length=50)),
                (
                    "service_tier1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier1",
                        to="landing.servicetier",
                        verbose_name="Tier 3",
                    ),
                ),
                (
                    "service_tier2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier2",
                        to="landing.servicetier",
                        verbose_name="Tier 3",
                    ),
                ),
                (
                    "service_tier3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier3",
                        to="landing.servicetier",
                        verbose_name="Tier 3",
                    ),
                ),
            ],
        ),
    ]
