# Generated by Django 4.1.3 on 2023-03-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_alter_servicetablelabels_tier1_icon_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetablelabels",
            options={
                "verbose_name": "Service Table Labels",
                "verbose_name_plural": "Service Table Labels",
            },
        ),
    ]
