# Generated by Django 4.1.3 on 2023-03-07 14:45

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0023_alter_servicetier_options"),
        ("services", "0017_alter_servicetablelabels_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier1",
            field=api.customs.CustomForeignKeyField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier1",
                to="landing.servicetier",
                verbose_name="Tier 1",
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier2",
            field=api.customs.CustomForeignKeyField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier2",
                to="landing.servicetier",
                verbose_name="Tier 2",
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier3",
            field=api.customs.CustomForeignKeyField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier3",
                to="landing.servicetier",
                verbose_name="Tier 3",
            ),
        ),
    ]
