# Generated by Django 4.1.3 on 2023-03-07 15:05

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_alter_servicetablelabels_service_tier1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCompareRows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    api.customs.CustomCharField(max_length=40, verbose_name="Feature"),
                ),
                (
                    "tier1_value",
                    api.customs.CustomCharField(max_length=100, verbose_name="Tier 1"),
                ),
                (
                    "tier2_value",
                    api.customs.CustomCharField(max_length=100, verbose_name="Tier 2"),
                ),
                (
                    "tier3_value",
                    api.customs.CustomCharField(max_length=100, verbose_name="Tier 3"),
                ),
            ],
            options={
                "verbose_name": "Service Compare Rows",
                "verbose_name_plural": "Service Compare Rows",
            },
        ),
    ]
