# Generated by Django 4.1.3 on 2023-03-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_servicecomparerows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecomparerows",
            options={
                "verbose_name": "Service Table Rows",
                "verbose_name_plural": "Service Table Rows",
            },
        ),
    ]
