# Generated by Django 4.1.3 on 2023-03-14 20:08

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0020_alter_servicecomparerows_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefits",
            name="description",
            field=api.customs.CustomTextField(
                max_length=250, verbose_name="Description"
            ),
        ),
    ]
