# Generated by Django 4.1.3 on 2023-03-19 20:27

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0022_alter_benefits_buttontext_alter_benefits_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetable",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Top Header Display of Hero Section",
                max_length=20,
                null=True,
                verbose_name="Table Name",
            ),
        ),
    ]
