# Generated by Django 4.1.3 on 2023-03-19 22:04

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_alter_servicetable_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetablelabels",
            name="name",
            field=api.customs.CustomCharField(
                default="Test", max_length=40, verbose_name="Set Name"
            ),
        ),
        migrations.AlterField(
            model_name="servicetable",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Top Header Display of Hero Section",
                max_length=20,
                verbose_name="Table Name",
            ),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier1",
            field=api.customs.CustomCharField(max_length=40, verbose_name="Tier 1"),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier2",
            field=api.customs.CustomCharField(max_length=40, verbose_name="Tier 2"),
        ),
        migrations.AlterField(
            model_name="servicetablelabels",
            name="service_tier3",
            field=api.customs.CustomCharField(max_length=40, verbose_name="Tier 3"),
        ),
    ]
