# Generated by Django 4.1.3 on 2023-03-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_alter_answerchoice_question_alter_question_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_set",
        ),
        migrations.RemoveField(
            model_name="questionset",
            name="questionnaire",
        ),
        migrations.DeleteModel(
            name="AnswerChoice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Questionnaire",
        ),
        migrations.DeleteModel(
            name="QuestionSet",
        ),
    ]
