# Generated by Django 4.1.3 on 2023-03-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0029_remove_question_question_set_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicetable",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="servicetable",
            name="rows",
        ),
        migrations.DeleteModel(
            name="ServiceCompareRows",
        ),
        migrations.DeleteModel(
            name="ServiceTable",
        ),
        migrations.DeleteModel(
            name="ServiceTableLabels",
        ),
    ]
