# Generated by Django 4.1.3 on 2023-03-21 04:17

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0030_remove_servicetable_labels_remove_servicetable_rows_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="benefits",
            name="page_link",
            field=api.customs.CustomCharField(
                default="about",
                help_text="Help Text Placeholder",
                max_length=40,
                verbose_name="Page Link",
            ),
        ),
    ]
