# Generated by Django 4.1.3 on 2023-03-25 15:02

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0027_alter_feature_detail_alter_heroblock_buttontext_and_more"),
        ("services", "0031_benefits_page_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefits",
            name="buttonText",
            field=api.customs.CustomCharField(
                help_text="Button Text", max_length=40, verbose_name="Button Text"
            ),
        ),
        migrations.AlterField(
            model_name="benefits",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Description", max_length=250, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="benefits",
            name="icon",
            field=api.customs.CustomCharField(
                help_text="Select Icon", max_length=40, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="benefits",
            name="page_link",
            field=api.customs.CustomCharField(
                default="about",
                help_text="Button Link",
                max_length=40,
                verbose_name="Page Link",
            ),
        ),
        migrations.AlterField(
            model_name="benefits",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Title", max_length=100, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="processimageitem",
            name="servicetier",
            field=models.ForeignKey(
                help_text="Service Tier Link",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicetier",
                to="landing.servicetier",
                verbose_name="Service Tier",
            ),
        ),
        migrations.AlterField(
            model_name="processtextitem",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Description", max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="processtextitem",
            name="icon",
            field=api.customs.CustomCharField(
                help_text="Select Icon", max_length=40, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="processtextitem",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Header", max_length=100, verbose_name="Title"
            ),
        ),
    ]
