# Generated by Django 4.1.3 on 2023-03-26 02:21

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0032_alter_benefits_buttontext_alter_benefits_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefits",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Content Text", max_length=250, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="benefits",
            name="page_link",
            field=api.customs.CustomCharField(
                default="about",
                help_text="Page Link",
                max_length=40,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="benefits",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Header Text", max_length=100, verbose_name="Header"
            ),
        ),
    ]
