# Generated by Django 4.1.3 on 2023-03-29 01:31

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0006_alter_servicetable_labels_alter_servicetable_rows"),
        ("landing", "0035_alter_latestnews_latest_articles"),
        ("quizes", "0009_alter_answerchoice_text_alter_question_text"),
        (
            "services",
            "0033_alter_benefits_description_alter_benefits_page_link_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        default="Placeholder",
                        help_text="Hero Name",
                        max_length=20,
                        verbose_name="Hero Name",
                    ),
                ),
                ("benefits", models.ManyToManyField(to="services.benefits")),
                (
                    "competitors_table",
                    models.ForeignKey(
                        limit_choices_to={"name": "Competitors"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="tables.servicetable",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        limit_choices_to={"slug": "service-quiz"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizes.questionnaire",
                    ),
                ),
                ("service_tiers", models.ManyToManyField(to="landing.servicetier")),
                (
                    "tiers_table",
                    models.ForeignKey(
                        limit_choices_to={"name": "Tiers"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="tables.servicetable",
                    ),
                ),
                (
                    "title_block",
                    models.ForeignKey(
                        limit_choices_to={"name": "benefits"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.titleblock",
                    ),
                ),
            ],
        ),
    ]
