# Generated by Django 4.1.3 on 2023-04-04 03:36

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0034_quiz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Quiz", "verbose_name_plural": "Quizes"},
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Referential Name",
                max_length=20,
                verbose_name="Referential Name",
            ),
        ),
    ]
