# Generated by Django 4.1.3 on 2023-04-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0035_alter_quiz_options_alter_quiz_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processtextitem",
            options={
                "ordering": ["title"],
                "verbose_name": "Process Text Item",
                "verbose_name_plural": "Process Text Items",
            },
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ["name"],
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizes",
            },
        ),
    ]
