# Generated by Django 4.1.3 on 2023-03-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="reactcomponent",
            name="source_object",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="component_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="reactcomponent",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.datasource",
            ),
        ),
    ]
