# Generated by Django 4.1.3 on 2023-03-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0002_datasource_reactcomponent_source_object_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reactcomponent",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="reactcomponent",
            name="source_object",
        ),
        migrations.AddField(
            model_name="reactcomponent",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="reactcomponent",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
    ]
