# Generated by Django 4.1.3 on 2023-03-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0003_remove_reactcomponent_data_source_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reactcomponent",
            old_name="object_id",
            new_name="data_source_id",
        ),
        migrations.RemoveField(
            model_name="reactcomponent",
            name="content_type",
        ),
        migrations.AddField(
            model_name="reactcomponent",
            name="data_source_type",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
