# Generated by Django 4.1.3 on 2023-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_remove_reactcomponent_data_source_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactcomponent",
            name="component_name",
            field=models.CharField(
                choices=[
                    ("ServiceTier", "ServiceTier"),
                    ("Value", "Value"),
                    ("About", "About"),
                    ("FAQ", "FAQ"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="props",
            field=models.JSONField(default=dict),
        ),
    ]
