# Generated by Django 4.1.3 on 2023-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_reactcomponent_component_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactcomponent",
            name="query_set",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="component_name",
            field=models.CharField(
                choices=[
                    ("ServiceTier", "ServiceTier"),
                    ("Value", "Value"),
                    ("About", "About"),
                    ("FAQ", "FAQ"),
                    ("Hero", "Hero"),
                ],
                max_length=50,
            ),
        ),
    ]
