# Generated by Django 4.1.3 on 2023-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_reactcomponent_query_set_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactcomponent",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
