# Generated by Django 4.1.3 on 2023-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_reactcomponent_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactcomponent",
            name="query_set",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
