# Generated by Django 4.1.3 on 2023-03-28 22:38

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_alter_reactcomponent_component_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactcomponent",
            name="component_name",
            field=models.CharField(
                choices=[
                    ("ServiceTier", "ServiceTier"),
                    ("Value", "Value"),
                    ("About", "About"),
                    ("FAQ", "FAQ"),
                    ("Hero", "Hero"),
                    ("Processes", "Processes"),
                    ("LatestNews", "LatestNews"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="props",
            field=models.JSONField(default=dict, verbose_name="Props"),
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="query_set",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Query Option",
                max_length=50,
                null=True,
                verbose_name="Query Option",
            ),
        ),
    ]
