# Generated by Django 4.1.3 on 2023-03-29 01:31

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_reactcomponent_component_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reactcomponent",
            options={"verbose_name": "Components", "verbose_name_plural": "Components"},
        ),
        migrations.AlterModelOptions(
            name="reactpage",
            options={"verbose_name": "Pages", "verbose_name_plural": "Pages"},
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="component_name",
            field=models.CharField(
                choices=[
                    ("ServiceTier", "ServiceTier"),
                    ("Value", "Value"),
                    ("About", "About"),
                    ("FAQ", "FAQ"),
                    ("Hero", "Hero"),
                    ("Processes", "Processes"),
                    ("LatestNews", "LatestNews"),
                    ("NewsletterForm", "NewsletterForm"),
                    ("IconScroller", "IconScroller"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="props",
            field=models.JSONField(blank=True, default=dict, verbose_name="Props"),
        ),
        migrations.AlterField(
            model_name="reactpage",
            name="components",
            field=models.ManyToManyField(
                help_text="Components",
                to="pages.reactcomponent",
                verbose_name="Components",
            ),
        ),
        migrations.AlterField(
            model_name="reactpage",
            name="page_name",
            field=api.customs.CustomCharField(
                help_text="Page Name", max_length=50, verbose_name="Page Name"
            ),
        ),
    ]
