# Generated by Django 4.1.3 on 2023-03-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_alter_reactcomponent_options_alter_reactpage_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReactPage",
            new_name="Page",
        ),
        migrations.AlterField(
            model_name="reactcomponent",
            name="component_name",
            field=models.CharField(
                choices=[
                    ("ServiceTier", "ServiceTier"),
                    ("Value", "Value"),
                    ("About", "About"),
                    ("FAQ", "FAQ"),
                    ("Hero", "Hero"),
                    ("Processes", "Processes"),
                    ("LatestNews", "LatestNews"),
                    ("NewsletterForm", "NewsletterForm"),
                    ("IconScroller", "IconScroller"),
                    ("Quiz", "Quiz"),
                ],
                max_length=50,
            ),
        ),
    ]
