# Generated by Django 4.1.3 on 2023-03-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_rename_reactpage_page_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReactComponent",
            new_name="Component",
        ),
    ]
