# Generated by Django 4.1.3 on 2023-03-30 01:10

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_rename_reactcomponent_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="verbose_name",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Page Display Name",
                max_length=50,
                verbose_name="Page Display Name",
            ),
        ),
    ]
