# Generated by Django 4.1.3 on 2023-03-30 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0018_alter_component_component_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="component_name",
            field=models.CharField(
                choices=[
                    ("ServiceTier", "ServiceTier"),
                    ("Value", "Value"),
                    ("About", "About"),
                    ("FAQ", "FAQ"),
                    ("Hero", "Hero"),
                    ("Processes", "Processes"),
                    ("LatestNews", "LatestNews"),
                    ("NewsletterForm", "NewsletterForm"),
                    ("IconScroller", "IconScroller"),
                    ("Quiz", "Quiz"),
                    ("TeamMember", "TeamMember"),
                    ("JobPosting", "JobPosting"),
                    ("ContactInformation", "ContactInformation"),
                    ("Socials", "Socials"),
                    ("Hours", "Hours"),
                    ("Contact", "Contact"),
                    ("Articles", "Articles"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ComponentObj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "query_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Query parameters to filter the data source",
                        verbose_name="Query Parameters",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "content",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "myapp")),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Component Name",
                    ),
                ),
            ],
        ),
    ]
