# Generated by Django 4.1.3 on 2023-03-31 00:10

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0019_alter_component_component_name_componentobj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentobj",
            name="content",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("app_label__in", {"general", "jobs"})),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Data Model Name",
            ),
        ),
        migrations.CreateModel(
            name="PageObj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_name",
                    api.customs.CustomCharField(
                        help_text="Page Name", max_length=50, verbose_name="Page Name"
                    ),
                ),
                (
                    "verbose_name",
                    api.customs.CustomCharField(
                        default="Placeholder",
                        help_text="Page Display Name",
                        max_length=50,
                        verbose_name="Page Display Name",
                    ),
                ),
                (
                    "components",
                    models.ManyToManyField(
                        help_text="Components",
                        to="pages.componentobj",
                        verbose_name="Components",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pages",
                "verbose_name_plural": "Pages",
            },
        ),
    ]
