# Generated by Django 4.1.3 on 2023-04-03 15:24

import api.customs
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0020_alter_componentobj_content_pageobj"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Category Name")),
            ],
        ),
        migrations.AlterModelOptions(
            name="componentobj",
            options={
                "verbose_name": "Components2",
                "verbose_name_plural": "Components2",
            },
        ),
        migrations.AlterModelOptions(
            name="pageobj",
            options={"verbose_name": "Pages2", "verbose_name_plural": "Pages2"},
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="content",
            field=models.ForeignKey(
                limit_choices_to=pages.models.allowed_content_types,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Data Model Name",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Component Name", max_length=50, verbose_name="Component Name"
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="order",
            field=api.customs.CustomPositiveIntegerField(
                default=0, verbose_name="Page Appearance Order"
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="query_params",
            field=api.customs.CustomJSONField(
                blank=True,
                default=dict,
                help_text="Query parameters to filter the data source",
                verbose_name="Query Parameters",
            ),
        ),
        migrations.AddField(
            model_name="componentobj",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
    ]
