# Generated by Django 4.1.3 on 2023-04-03 15:56

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_componentcategory_alter_componentobj_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="componentcategory",
            options={
                "verbose_name": "Component Category",
                "verbose_name_plural": "Component Category",
            },
        ),
        migrations.AlterField(
            model_name="componentcategory",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Category Name", max_length=50, verbose_name="Category Name"
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "Contact",
                        "Landing",
                        "About",
                        "Heading",
                        "Card",
                        "Text",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.CreateModel(
            name="PageSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_name",
                    api.customs.CustomCharField(
                        help_text="Set Name", max_length=50, verbose_name="Set Name"
                    ),
                ),
                (
                    "pages",
                    models.ManyToManyField(
                        help_text="Pages in this set",
                        to="pages.pageobj",
                        verbose_name="Pages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Set",
                "verbose_name_plural": "Page Sets",
            },
        ),
    ]
