# Generated by Django 4.1.3 on 2023-04-03 18:07

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0024_alter_app_options_app_nav_component_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="error_component",
            field=api.customs.CustomCharField(
                blank=True,
                choices=[("Standard", "Standard")],
                help_text="Error Component Choice",
                max_length=10,
                null=True,
                verbose_name="Error Component",
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="fab_component",
            field=api.customs.CustomCharField(
                blank=True,
                choices=[("Standard", "Standard")],
                help_text="FAB Component Choice",
                max_length=10,
                null=True,
                verbose_name="FAB Component",
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="footer_component",
            field=api.customs.CustomCharField(
                blank=True,
                choices=[("Standard", "Standard")],
                help_text="Footer Component Choice",
                max_length=10,
                null=True,
                verbose_name="Footer Component",
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="loading_component",
            field=api.customs.CustomCharField(
                blank=True,
                choices=[("Standard", "Standard")],
                help_text="Loading Component Choice",
                max_length=10,
                null=True,
                verbose_name="Loading Component",
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="nav_component",
            field=api.customs.CustomCharField(
                blank=True,
                choices=[("Standard", "Standard")],
                help_text="Navigation Component Choice",
                max_length=10,
                null=True,
                verbose_name="Navigation Component",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "Contact",
                        "Landing",
                        "About",
                        "Heading",
                        "Card",
                        "Text",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
    ]
