# Generated by Django 4.1.3 on 2023-04-04 03:36

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0031_pageobj_access_alter_app_contact_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "Contact",
                        "Landing",
                        "About",
                        "Heading",
                        "Card",
                        "Text",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.AlterField(
            model_name="pageobj",
            name="access",
            field=api.customs.CustomCharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                    ("admin", "Admin"),
                ],
                default="Public",
                help_text="Page Access Level",
                max_length=10,
                verbose_name="Page Access Level",
            ),
        ),
    ]
