# Generated by Django 4.1.3 on 2023-04-04 21:50

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0037_alter_componentobj_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={
                "ordering": ["app_name"],
                "verbose_name": "App",
                "verbose_name_plural": "App",
            },
        ),
        migrations.AlterModelOptions(
            name="componentcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Component Category",
                "verbose_name_plural": "Component Category",
            },
        ),
        migrations.AlterModelOptions(
            name="componentobj",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Components2",
                "verbose_name_plural": "Components2",
            },
        ),
        migrations.AlterModelOptions(
            name="pageobj",
            options={
                "ordering": ["verbose_name", "access"],
                "verbose_name": "Pages2",
                "verbose_name_plural": "Pages2",
            },
        ),
        migrations.AlterModelOptions(
            name="pageset",
            options={
                "ordering": ["set_name"],
                "verbose_name": "Page Set",
                "verbose_name_plural": "Page Sets",
            },
        ),
        migrations.AlterField(
            model_name="app",
            name="app_name",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="App Name",
                max_length=50,
                unique=True,
                verbose_name="App Name",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "About",
                        "Card",
                        "Contact",
                        "Heading",
                        "Landing",
                        "Text",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="Component Name",
                max_length=50,
                verbose_name="Component Name",
            ),
        ),
        migrations.AlterField(
            model_name="pageobj",
            name="page_name",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="Page Name",
                max_length=50,
                verbose_name="Page Name",
            ),
        ),
        migrations.AlterField(
            model_name="pageobj",
            name="verbose_name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Page Display Name",
                max_length=50,
                verbose_name="Page Display Name",
            ),
        ),
    ]
