# Generated by Django 4.1.3 on 2023-04-04 22:26

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0038_alter_app_options_alter_componentcategory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="components",
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "About",
                        "Card",
                        "Contact",
                        "Heading",
                        "Landing",
                        "Text",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.DeleteModel(
            name="Component",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
