# Generated by Django 4.1.3 on 2023-04-05 15:58

import api.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("pages", "0039_remove_page_components_alter_componentobj_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentobj",
            name="active",
            field=api.customs.CustomBooleanField(
                default=True, help_text="Active Status", verbose_name="Active"
            ),
        ),
        migrations.AddField(
            model_name="componentobj",
            name="author",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="componentobj",
            name="created_at",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="componentobj",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="componentobj",
            name="updated_at",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "About",
                        "Card",
                        "Contact",
                        "Heading",
                        "Landing",
                        "Text",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="content",
            field=api.customs.CustomForeignKeyField(
                limit_choices_to=pages.models.allowed_content_types,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="data",
                to="contenttypes.contenttype",
                verbose_name="Data Model",
            ),
        ),
    ]
