# Generated by Django 4.1.3 on 2023-04-05 16:29

import api.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0040_componentobj_active_componentobj_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageobj",
            name="author",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="pageobj",
            name="created_at",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="pageobj",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="pageobj",
            name="featured",
            field=api.customs.CustomBooleanField(
                default=True, help_text="Featured Status", verbose_name="Featured"
            ),
        ),
        migrations.AddField(
            model_name="pageobj",
            name="updated_at",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "About",
                        "Card",
                        "Contact",
                        "Heading",
                        "Landing",
                        "Text",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
