# Generated by Django 4.1.3 on 2023-04-05 18:05

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0041_pageobj_author_pageobj_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageobj",
            name="slug",
            field=api.customs.CustomCharField(
                blank=True,
                db_index=True,
                help_text="Page URL Slug",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Page URL Slug",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "About",
                        "Ass",
                        "Boobs",
                        "Card",
                        "Contact",
                        "Heading",
                        "Landing",
                        "Poop",
                        "Texas",
                        "Text",
                        "Tits",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.AlterField(
            model_name="pageobj",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageobj",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
