# Generated by Django 4.1.3 on 2023-04-05 18:11

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0042_pageobj_slug_alter_componentobj_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pageobj",
            options={
                "ordering": ["page_name", "access"],
                "verbose_name": "Pages2",
                "verbose_name_plural": "Pages2",
            },
        ),
        migrations.RemoveField(
            model_name="pageobj",
            name="verbose_name",
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "About",
                        "Ass",
                        "Boobs",
                        "Card",
                        "Contact",
                        "Heading",
                        "Landing",
                        "Poop",
                        "Texas",
                        "Text",
                        "Tits",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
        migrations.AlterField(
            model_name="pageobj",
            name="access",
            field=api.customs.CustomCharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                    ("admin", "Admin"),
                ],
                default="Public",
                help_text="Access Level",
                max_length=10,
                verbose_name="Access Level",
            ),
        ),
        migrations.AlterField(
            model_name="pageobj",
            name="slug",
            field=api.customs.CustomCharField(
                blank=True,
                db_index=True,
                help_text="URL Slug",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="URL Slug",
            ),
        ),
    ]
