# Generated by Django 4.1.3 on 2023-04-06 23:22

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0089_app_snackbar_component_alter_componentobj_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="not_found_component",
            field=api.customs.CustomCharField(
                blank=True,
                choices=[("Standard", "Standard"), ("Minimal", "Minimal")],
                help_text="404 Not Found Component Choice",
                max_length=10,
                null=True,
                verbose_name="404 Not Found Component",
            ),
        ),
        migrations.AlterField(
            model_name="componentobj",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={
                    "name__in": (
                        "About",
                        "Ass",
                        "Boobs",
                        "Card",
                        "Contact",
                        "Heading",
                        "Landing",
                        "Poop",
                        "Texas",
                        "Text",
                        "Tits",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="pages.componentcategory",
                verbose_name="Component Category",
            ),
        ),
    ]
