# Generated by Django 4.1.3 on 2023-03-20 01:59

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    api.customs.CustomCharField(
                        help_text="Top Header Display of Hero Section",
                        max_length=255,
                        verbose_name="Questionnaire Name",
                    ),
                ),
                (
                    "slug",
                    api.customs.CustomSlugField(
                        help_text="Help Text Placeholder",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        help_text="Help Text Placeholder",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.CreateModel(
            name="QuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    api.customs.CustomCharField(
                        help_text="Top Header Display of Hero Section",
                        max_length=255,
                        verbose_name="Question Set Title",
                    ),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        help_text="Help Text Placeholder",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    api.customs.CustomPositiveIntegerField(
                        default=0,
                        help_text="Top Header Display of Hero Section",
                        verbose_name="Question Set Ordering",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_sets",
                        to="quizes.questionnaire",
                        verbose_name="Questionnaire Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Set",
                "verbose_name_plural": "Question Sets",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    api.customs.CustomCharField(
                        help_text="Top Header Display of Hero Section",
                        max_length=255,
                        verbose_name="Question Text",
                    ),
                ),
                (
                    "order",
                    api.customs.CustomPositiveIntegerField(
                        default=0,
                        help_text="Top Header Display of Hero Section",
                        verbose_name="Question Ordering",
                    ),
                ),
                (
                    "question_set",
                    api.customs.CustomForeignKeyField(
                        help_text="Top Header Display of Hero Section",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizes.questionset",
                        verbose_name="Question Set Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    api.customs.CustomCharField(
                        help_text="Top Header Display of Hero Section",
                        max_length=255,
                        verbose_name="Answer Text",
                    ),
                ),
                (
                    "value",
                    api.customs.CustomDecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Top Header Display of Hero Section",
                        max_digits=8,
                        verbose_name="Answer Value",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Top Header Display of Hero Section",
                        verbose_name="Answer Ordering",
                    ),
                ),
                (
                    "question",
                    api.customs.CustomForeignKeyField(
                        help_text="Top Header Display of Hero Section",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_choices",
                        to="quizes.question",
                        verbose_name="Question Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Choice",
                "verbose_name_plural": "Answer Choices",
                "ordering": ["order"],
            },
        ),
    ]
