# Generated by Django 4.1.3 on 2023-03-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0003_alter_questionnaireresultanswer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireresults",
            name="contact_email",
            field=models.EmailField(default="Tom@tom.com", max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaireresults",
            name="contact_name",
            field=models.CharField(default="Tom", max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaireresults",
            name="contact_phone",
            field=models.CharField(default="555-555-5555", max_length=20),
        ),
        migrations.AddField(
            model_name="questionnaireresults",
            name="contact_state",
            field=models.CharField(default="TN", max_length=20),
        ),
        migrations.AddField(
            model_name="questionnaireresults",
            name="contact_time",
            field=models.CharField(default="2PM", max_length=200),
        ),
    ]
