# Generated by Django 4.1.3 on 2023-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0005_remove_questionnaireresults_contact_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_state",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
