# Generated by Django 4.1.3 on 2023-03-26 02:21

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0007_question_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerchoice",
            name="order",
            field=api.customs.CustomPositiveIntegerField(
                default=0, help_text="Answer Ordering", verbose_name="Answer Ordering"
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="question",
            field=api.customs.CustomForeignKeyField(
                help_text="Linked Question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_choices",
                to="quizes.question",
                verbose_name="Question Link",
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="text",
            field=api.customs.CustomCharField(
                help_text="Answer Text", max_length=255, verbose_name="Answer Text"
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="value",
            field=api.customs.CustomDecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Answer Value",
                max_digits=8,
                verbose_name="Answer Value",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=api.customs.CustomPositiveIntegerField(
                default=0,
                help_text="Question Ordering",
                verbose_name="Question Ordering",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_set",
            field=api.customs.CustomForeignKeyField(
                help_text="Linked Question Set",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizes.questionset",
                verbose_name="Question Set Link",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=api.customs.CustomSlugField(
                default="Placeholder", help_text="Identifier", verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=api.customs.CustomCharField(
                help_text="Question Text", max_length=255, verbose_name="Question Text"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Description", max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="slug",
            field=api.customs.CustomSlugField(
                help_text="Identifier", unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Questionnaire Name",
                max_length=255,
                verbose_name="Questionnaire Name",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresultanswer",
            name="answer_choice",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked Answer Choice",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizes.answerchoice",
                verbose_name="Answer Choice",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresultanswer",
            name="answer_choice_text",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Answer Choice Text",
                max_length=255,
                null=True,
                verbose_name="Answer Choice Text",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresultanswer",
            name="question",
            field=models.ForeignKey(
                help_text="Linked Question",
                on_delete=django.db.models.deletion.CASCADE,
                to="quizes.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresultanswer",
            name="question_text",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Question Text",
                max_length=255,
                null=True,
                verbose_name="Question Text",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresultanswer",
            name="questionnaire_result",
            field=models.ForeignKey(
                help_text="Linked Questionnaire Results",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="quizes.questionnaireresults",
                verbose_name="Questionnaire Results",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_email",
            field=api.customs.CustomEmailField(
                help_text="Contact Email Address",
                max_length=255,
                verbose_name="Contact Email",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_name",
            field=api.customs.CustomCharField(
                help_text="Contact Full Name",
                max_length=255,
                verbose_name="Contact Name",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_phone",
            field=api.customs.CustomCharField(
                help_text="Contact Phone Number",
                max_length=20,
                null=True,
                verbose_name="Contact Phone",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="contact_state",
            field=api.customs.CustomCharField(
                help_text="Contact State of Residence",
                max_length=20,
                null=True,
                verbose_name="Contact State",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresults",
            name="questionnaire",
            field=models.ForeignKey(
                help_text="Linked Questionnaire",
                on_delete=django.db.models.deletion.CASCADE,
                to="quizes.questionnaire",
                verbose_name="Questionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="description",
            field=api.customs.CustomTextField(
                help_text="Description", max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="order",
            field=api.customs.CustomPositiveIntegerField(
                default=0,
                help_text="Display Order",
                verbose_name="Question Set Ordering",
            ),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="questionnaire",
            field=models.ForeignKey(
                help_text="Test",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_sets",
                to="quizes.questionnaire",
                verbose_name="Questionnaire Link",
            ),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="title",
            field=api.customs.CustomCharField(
                help_text="Question Set Title",
                max_length=255,
                verbose_name="Question Set Title",
            ),
        ),
    ]
