# Generated by Django 4.1.3 on 2023-04-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0009_alter_answerchoice_text_alter_question_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerchoice",
            options={
                "ordering": ["question"],
                "verbose_name": "Answer Choice",
                "verbose_name_plural": "Answer Choices",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnaire",
            options={
                "ordering": ["slug"],
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnaireresults",
            options={
                "ordering": ["questionnaire", "contact_name"],
                "verbose_name": "Questionnaire Results",
                "verbose_name_plural": "Questionnaire Results",
            },
        ),
        migrations.AlterModelOptions(
            name="questionset",
            options={
                "ordering": ["title"],
                "verbose_name": "Question Set",
                "verbose_name_plural": "Question Sets",
            },
        ),
    ]
