# Generated by Django 4.1.3 on 2023-04-12 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["id"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="taskcategory",
            options={
                "ordering": ["id"],
                "verbose_name": "Task Category",
                "verbose_name_plural": "Task Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="tasklist",
            options={
                "ordering": ["id"],
                "verbose_name": "Task List",
                "verbose_name_plural": "Task Lists",
            },
        ),
        migrations.RenameField(
            model_name="task",
            old_name="created_by",
            new_name="author",
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("Incomplete", "Incomplete"), ("Complete", "Complete")],
                default="Incomplete",
                max_length=20,
            ),
        ),
    ]
