# Generated by Django 4.1.3 on 2023-04-16 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_alter_task_options_alter_taskcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TaskSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="get_task_lists", to="tasks.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Section",
                "verbose_name_plural": "Task Sections",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TaskList2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        related_name="task_sections", to="tasks.tasksection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task List",
                "verbose_name_plural": "Task Lists",
                "ordering": ["id"],
            },
        ),
    ]
