# Generated by Django 4.1.3 on 2023-04-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_task_task_category_delete_taskcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskList",
        ),
    ]
