# Generated by Django 4.1.3 on 2023-04-17 14:13

import api.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0006_rename_tasklist2_tasklist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tasklist",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tasksection",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="author",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=api.customs.CustomCharField(
                choices=[
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                ],
                default="None",
                help_text="Task Priority",
                max_length=10,
                verbose_name="Task Priority",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=api.customs.CustomCharField(
                choices=[("Incomplete", "Incomplete"), ("Complete", "Complete")],
                default="Incomplete",
                help_text="Task Status",
                max_length=20,
                verbose_name="Task Status",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Task Title",
                max_length=100,
                verbose_name="Task Title",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="author",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="title",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Task List Title",
                max_length=100,
                verbose_name="Task List Title",
            ),
        ),
        migrations.AlterField(
            model_name="tasksection",
            name="author",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="tasksection",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="tasksection",
            name="title",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Section Title",
                max_length=100,
                verbose_name="Section Title",
            ),
        ),
    ]
