# Generated by Django 4.1.3 on 2023-02-22 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0003_article_is_highlighted"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Articles",
        ),
    ]
