# Generated by Django 4.1.3 on 2023-02-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_rename_article_articles"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Tags",
        ),
    ]
