# Generated by Django 4.1.3 on 2023-02-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_rename_tag_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Articles", "verbose_name_plural": "Articles"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Tags", "verbose_name_plural": "Tags"},
        ),
    ]
