# Generated by Django 4.1.3 on 2023-02-27 15:58

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_articles_options_alter_tags_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=api.customs.CustomCharField(max_length=255, verbose_name="Item Name"),
        ),
    ]
