# Generated by Django 4.1.3 on 2023-03-06 00:18

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_alter_tags_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=api.customs.CustomCharField(max_length=255, verbose_name="Tag Name"),
        ),
    ]
