# Generated by Django 4.1.3 on 2023-03-19 19:32

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_alter_tags_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="title",
            field=api.customs.CustomCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=api.customs.CustomCharField(
                help_text="Help Text Placeholder",
                max_length=255,
                verbose_name="Tag Name",
            ),
        ),
    ]
