# Generated by Django 4.1.3 on 2023-03-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articles_title_alter_tags_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tags",
            old_name="name",
            new_name="detail",
        ),
    ]
