# Generated by Django 4.1.3 on 2023-03-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_rename_name_tags_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="tags",
            field=models.ManyToManyField(
                related_name="articles", to="articles.tags", verbose_name="Tags"
            ),
        ),
    ]
