# Generated by Django 4.1.3 on 2023-02-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_themesettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="themesettings",
            old_name="default_color",
            new_name="secondary_color",
        ),
    ]
