# Generated by Django 4.1.3 on 2023-02-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_rename_default_color_themesettings_secondary_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themesettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theme_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
