# Generated by Django 4.1.3 on 2023-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_alter_themesettings_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
