# Generated by Django 4.1.3 on 2023-03-07 21:36

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0006_delete_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    api.customs.CustomCharField(max_length=20, verbose_name="Page"),
                ),
                (
                    "title",
                    api.customs.CustomCharField(max_length=30, verbose_name="Title"),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        max_length=300, verbose_name="Description"
                    ),
                ),
                (
                    "keywords",
                    api.customs.CustomCharField(
                        max_length=100, verbose_name="Keywords"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Image")),
                ("url", models.URLField(verbose_name="URL")),
            ],
            options={
                "verbose_name": "Headers",
                "verbose_name_plural": "Headers",
            },
        ),
    ]
