# Generated by Django 4.1.3 on 2023-03-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0008_delete_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="salt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
