# Generated by Django 4.1.3 on 2023-03-14 20:08

import api.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0011_user_address_user_city_user_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="themesettings",
            options={
                "verbose_name": "Theme Settings",
                "verbose_name_plural": "Theme Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenblacklist",
            options={
                "verbose_name": "Token Blacklist",
                "verbose_name_plural": "Token Blacklist",
            },
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="background_color",
            field=api.customs.CustomCharField(max_length=7, verbose_name="Background"),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="primary_color",
            field=api.customs.CustomCharField(max_length=7, verbose_name="Primary"),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="secondary_color",
            field=api.customs.CustomCharField(max_length=7, verbose_name="Secondary"),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theme_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="tokenblacklist",
            name="blacklisted_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Blacklisted At"
            ),
        ),
        migrations.AlterField(
            model_name="tokenblacklist",
            name="token",
            field=api.customs.CustomTextField(
                max_length=500, unique=True, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=api.customs.CustomCharField(
                blank=True, max_length=255, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=api.customs.CustomEmailField(
                max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=api.customs.CustomCharField(
                max_length=255, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=api.customs.CustomCharField(max_length=255, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=api.customs.CustomCharField(max_length=255, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=api.customs.CustomCharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="salt",
            field=api.customs.CustomCharField(
                max_length=255, null=True, verbose_name="Salt"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=api.customs.CustomCharField(
                blank=True, max_length=100, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=api.customs.CustomCharField(
                max_length=255, unique=True, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip_code",
            field=api.customs.CustomCharField(
                blank=True, max_length=20, verbose_name="Zipcode"
            ),
        ),
    ]
