# Generated by Django 4.1.3 on 2023-04-04 03:57

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0014_alter_themesettings_background_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="themesettings",
            options={
                "ordering": ["user"],
                "verbose_name": "Theme Settings",
                "verbose_name_plural": "Theme Settings",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=api.customs.CustomCharField(
                db_index=True,
                help_text="Username",
                max_length=255,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
