# Generated by Django 4.1.3 on 2023-04-11 02:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faqs", "0002_rename_answer_faqanswer_rename_question_faqquestion_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FAQ",
            new_name="FAQSet",
        ),
    ]
