# Generated by Django 4.1.3 on 2023-04-11 02:24

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0003_rename_faq_faqset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faqquestionset",
            name="faq",
        ),
        migrations.AddField(
            model_name="faqquestionset",
            name="faqset",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_sets",
                related_query_name="faqset",
                to="faqs.faqset",
                verbose_name="FAQSet",
            ),
        ),
    ]
