# Generated by Django 4.1.3 on 2023-04-11 02:43

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0004_remove_faqquestionset_faq_faqquestionset_faqset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqanswer",
            options={
                "ordering": ["-id"],
                "verbose_name": "FAQ Answer",
                "verbose_name_plural": "FAQ Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="faqquestion",
            options={
                "ordering": ["-id"],
                "verbose_name": "FAQ Question",
                "verbose_name_plural": "FAQ Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="faqquestioncategory",
            options={
                "ordering": ["-id"],
                "verbose_name": "FAQ Question Category",
                "verbose_name_plural": "FAQ Question Categorys",
            },
        ),
        migrations.AlterModelOptions(
            name="faqquestionset",
            options={
                "ordering": ["-id"],
                "verbose_name": "FAQ Question Set",
                "verbose_name_plural": "FAQ Question Sets",
            },
        ),
        migrations.AlterModelOptions(
            name="faqset",
            options={
                "ordering": ["-id"],
                "verbose_name": "FAQ Set",
                "verbose_name_plural": "FAQ Sets",
            },
        ),
        migrations.RemoveField(
            model_name="faqanswer",
            name="question",
        ),
        migrations.AddField(
            model_name="faqanswer",
            name="faq_question",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="faq_question",
                to="faqs.faqquestion",
                verbose_name="FAQ Question",
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionset",
            name="answer",
            field=api.customs.CustomForeignKeyField(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="set-answer",
                to="faqs.faqanswer",
                verbose_name="FAQ Answer",
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionset",
            name="category",
            field=api.customs.CustomForeignKeyField(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="category",
                to="faqs.faqquestioncategory",
                verbose_name="FAQ Question Category",
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionset",
            name="question",
            field=api.customs.CustomForeignKeyField(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="set-question",
                to="faqs.faqquestion",
                verbose_name="FAQ Question",
            ),
        ),
    ]
