# Generated by Django 4.1.3 on 2023-04-11 02:52

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0005_alter_faqanswer_options_alter_faqquestion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faqquestionset",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="faqquestionset",
            name="category",
        ),
        migrations.RemoveField(
            model_name="faqquestionset",
            name="question",
        ),
        migrations.AddField(
            model_name="faqquestionset",
            name="faq_answer",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="faq_answer",
                to="faqs.faqanswer",
                verbose_name="FAQ Answer",
            ),
        ),
        migrations.AddField(
            model_name="faqquestionset",
            name="faq_category",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="faq_category",
                to="faqs.faqquestioncategory",
                verbose_name="FAQ Question Category",
            ),
        ),
        migrations.AddField(
            model_name="faqquestionset",
            name="faq_question",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="faq_question",
                to="faqs.faqquestion",
                verbose_name="FAQ Question",
            ),
        ),
    ]
