# Generated by Django 4.1.3 on 2023-04-05 20:48

import api.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elements.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementSetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        help_text="Category Name",
                        max_length=50,
                        verbose_name="Category Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element Category",
                "verbose_name_plural": "Element Category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        db_index=True,
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                (
                    "order",
                    api.customs.CustomPositiveIntegerField(
                        default=0, verbose_name="Page Appearance Order"
                    ),
                ),
                (
                    "query_params",
                    api.customs.CustomJSONField(
                        blank=True,
                        default=dict,
                        help_text="Query parameters to filter the data source",
                        verbose_name="Query Parameters",
                    ),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Description (Optional)",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "active",
                    api.customs.CustomBooleanField(
                        default=True, help_text="Active Status", verbose_name="Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    api.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "content",
                    api.customs.CustomForeignKeyField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="data",
                        to="contenttypes.contenttype",
                        verbose_name="Data Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elements",
                "verbose_name_plural": "Elements",
                "ordering": ["name"],
            },
        ),
    ]
