# Generated by Django 4.1.3 on 2023-04-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0002_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Text",
            new_name="TextElement",
        ),
        migrations.AlterModelOptions(
            name="textelement",
            options={
                "verbose_name": "Text Element",
                "verbose_name_plural": "Text Elements",
            },
        ),
    ]
