# Generated by Django 4.1.3 on 2023-04-05 21:46

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0003_rename_text_textelement_alter_textelement_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        help_text="Category Name",
                        max_length=50,
                        verbose_name="Category Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element Category",
                "verbose_name_plural": "Element Category",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="elementsetcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Element Set Category",
                "verbose_name_plural": "Element Set Category",
            },
        ),
        migrations.AlterField(
            model_name="textelement",
            name="body",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Text Content",
                max_length=2000,
                null=True,
                verbose_name="Text Content",
            ),
        ),
    ]
