# Generated by Django 4.1.3 on 2023-04-05 21:46

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0004_elementcategory_alter_elementsetcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={"name__in": ()},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Element",
                to="elements.elementcategory",
                verbose_name="Element Category",
            ),
        ),
    ]
