# Generated by Django 4.1.3 on 2023-04-05 21:54

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0005_element_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={"name__in": ("Test", "Test2")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Element",
                to="elements.elementcategory",
                verbose_name="Element Category",
            ),
        ),
        migrations.CreateModel(
            name="ElementSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_name",
                    api.customs.CustomCharField(
                        help_text="Set Name", max_length=50, verbose_name="Set Name"
                    ),
                ),
                (
                    "elements",
                    models.ManyToManyField(
                        help_text="Elements in this set",
                        to="elements.element",
                        verbose_name="Elements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element Set",
                "verbose_name_plural": "Element Sets",
                "ordering": ["set_name"],
            },
        ),
    ]
