# Generated by Django 4.1.3 on 2023-04-06 00:15

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0010_elementitem_name_alter_element_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementitem",
            name="element_type",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Element Type",
                max_length=50,
                verbose_name="Element Type",
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={"name__in": ("Test", "Test2")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Element",
                to="elements.elementcategory",
                verbose_name="Element Category",
            ),
        ),
    ]
