# Generated by Django 4.1.3 on 2023-04-06 03:23

import api.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "elements",
            "0016_element2_name_headerelement2_name_imageelement2_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="category",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                limit_choices_to={"name__in": ("Test", "Test2")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Element",
                to="elements.elementcategory",
                verbose_name="Element Category",
            ),
        ),
        migrations.AlterField(
            model_name="elementset2",
            name="elements",
            field=models.ManyToManyField(to="elements.element2"),
        ),
    ]
