# Generated by Django 4.1.3 on 2023-04-06 04:06

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0017_alter_element_category_alter_elementset2_elements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elementitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="elementitem",
            name="element_set",
        ),
        migrations.RemoveField(
            model_name="textelement",
            name="element_set",
        ),
        migrations.AlterModelOptions(
            name="element2",
            options={
                "ordering": ["name"],
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="elementset2",
            options={
                "ordering": ["name"],
                "verbose_name": "Element Set",
                "verbose_name_plural": "Element Sets",
            },
        ),
        migrations.AlterModelOptions(
            name="headerelement2",
            options={
                "ordering": ["name"],
                "verbose_name": "Header Element",
                "verbose_name_plural": "Header Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="imageelement2",
            options={
                "ordering": ["name"],
                "verbose_name": "Image Element",
                "verbose_name_plural": "Image Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="textelement2",
            options={
                "ordering": ["name"],
                "verbose_name": "Text Element",
                "verbose_name_plural": "Text Elements",
            },
        ),
        migrations.AddField(
            model_name="element2",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="element2",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="element2",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="elementset2",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="elementset2",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="elementset2",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="headerelement2",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="headerelement2",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="headerelement2",
            name="order",
            field=api.customs.CustomPositiveIntegerField(
                default=0, verbose_name="Page Appearance Order"
            ),
        ),
        migrations.AddField(
            model_name="headerelement2",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="imageelement2",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="imageelement2",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="imageelement2",
            name="order",
            field=api.customs.CustomPositiveIntegerField(
                default=0, verbose_name="Page Appearance Order"
            ),
        ),
        migrations.AddField(
            model_name="imageelement2",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="textelement2",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="textelement2",
            name="description",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Description (Optional)",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="textelement2",
            name="order",
            field=api.customs.CustomPositiveIntegerField(
                default=0, verbose_name="Page Appearance Order"
            ),
        ),
        migrations.AddField(
            model_name="textelement2",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name="Element",
        ),
        migrations.DeleteModel(
            name="ElementCategory",
        ),
        migrations.DeleteModel(
            name="ElementItem",
        ),
        migrations.DeleteModel(
            name="ElementSet",
        ),
        migrations.DeleteModel(
            name="TextElement",
        ),
    ]
