# Generated by Django 4.1.3 on 2023-04-06 15:27

import api.customs
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elements", "0023_headerelement_author_imageelement_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="element",
            options={
                "ordering": ["-id"],
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="elementset",
            options={
                "ordering": ["-id"],
                "verbose_name": "Element Set",
                "verbose_name_plural": "Element Sets",
            },
        ),
        migrations.AlterModelOptions(
            name="elementsetcategory",
            options={
                "ordering": ["-id"],
                "verbose_name": "Element Set Category",
                "verbose_name_plural": "Element Set Category",
            },
        ),
        migrations.AlterModelOptions(
            name="headerelement",
            options={
                "ordering": ["-id"],
                "verbose_name": "Header Element",
                "verbose_name_plural": "Header Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="imageelement",
            options={
                "ordering": ["-id"],
                "verbose_name": "Image Element",
                "verbose_name_plural": "Image Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="textelement",
            options={
                "ordering": ["-id"],
                "verbose_name": "Text Element",
                "verbose_name_plural": "Text Elements",
            },
        ),
        migrations.AddField(
            model_name="element",
            name="author",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
    ]
