# Generated by Django 4.1.3 on 2023-04-06 15:35

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0024_alter_element_options_alter_elementset_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headerelement",
            name="type",
            field=api.customs.CustomCharField(
                choices=[
                    ("h1", "H1"),
                    ("h2", "H2"),
                    ("h3", "H3"),
                    ("h4", "H4"),
                    ("h5", "H5"),
                    ("h6", "H6"),
                ],
                default="h1",
                help_text="Header Type",
                max_length=2,
                verbose_name="Header Type",
            ),
        ),
    ]
