# Generated by Django 4.1.3 on 2023-04-06 15:45

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0026_imageelement_caption_imageelement_justify_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="subtype",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Element Subtype",
                max_length=10,
                verbose_name="Element Subtype",
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="type",
            field=api.customs.CustomCharField(
                default="Placeholder",
                help_text="Element Type",
                max_length=10,
                verbose_name="Element Type",
            ),
        ),
        migrations.AlterField(
            model_name="imageelement",
            name="type",
            field=api.customs.CustomCharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("full", "Full")],
                default="medium",
                help_text="Image Size",
                max_length=6,
                verbose_name="Image Size",
            ),
        ),
    ]
