# Generated by Django 4.1.3 on 2023-04-06 17:44

import api.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elements", "0030_imageelement_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Description (Optional)",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    api.customs.CustomPositiveIntegerField(
                        default=0, verbose_name="Page Appearance Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    api.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="textelement",
            name="type",
            field=api.customs.CustomCharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Light", "Light"),
                    ("Dense", "Dense"),
                ],
                default="Standard",
                help_text="Text Type",
                max_length=10,
                verbose_name="Text Type",
            ),
        ),
        migrations.CreateModel(
            name="ListElementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "element",
                    models.CharField(max_length=50, verbose_name="List Element"),
                ),
                (
                    "list_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_items",
                        to="elements.listelement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List Element Items",
                "ordering": ["order"],
            },
        ),
    ]
