# Generated by Django 4.1.3 on 2023-04-06 17:46

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0031_listelement_alter_textelement_type_listelementitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="listelement",
            name="type",
            field=api.customs.CustomCharField(
                choices=[
                    ("Unordered", "Unordered"),
                    ("Ordered", "Ordered"),
                    ("Icon", "Icon"),
                ],
                default="Unordered",
                help_text="List Type",
                max_length=10,
                verbose_name="List Type",
            ),
        ),
    ]
