# Generated by Django 4.1.3 on 2023-04-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0032_listelement_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listelement",
            options={
                "ordering": ["-id"],
                "verbose_name": "List Element",
                "verbose_name_plural": "List Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="listelementitem",
            options={
                "ordering": ["-id"],
                "verbose_name": "List Element Item",
                "verbose_name_plural": "List Element Items",
            },
        ),
    ]
