# Generated by Django 4.1.3 on 2023-04-06 17:57

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0033_alter_listelement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listelementitem",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="List Element Name",
                max_length=50,
                verbose_name="List Element Name",
            ),
        ),
    ]
