# Generated by Django 4.1.3 on 2023-04-06 18:06

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0034_listelementitem_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listelementitem",
            name="element",
        ),
        migrations.AddField(
            model_name="listelementitem",
            name="icon",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Select List Item Icon (Optional)",
                max_length=40,
                null=True,
                verbose_name="List Item Icon",
            ),
        ),
        migrations.AddField(
            model_name="listelementitem",
            name="primary",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Primary List Text",
                max_length=50,
                verbose_name="Primary List Text",
            ),
        ),
        migrations.AddField(
            model_name="listelementitem",
            name="secondary",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="Secondary List Text",
                max_length=50,
                verbose_name="Secondary List Text",
            ),
        ),
        migrations.AlterField(
            model_name="listelementitem",
            name="name",
            field=api.customs.CustomCharField(
                db_index=True,
                default="Placeholder",
                help_text="List Element Item Name",
                max_length=50,
                verbose_name="List Element Item Name",
            ),
        ),
    ]
