# Generated by Django 4.1.3 on 2023-04-06 20:35

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0036_remove_listelementitem_list_element_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListItemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        help_text="Tag Name", max_length=255, verbose_name="Tag Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "List Item Tag",
                "verbose_name_plural": "List Item Tags",
            },
        ),
    ]
