# Generated by Django 4.1.3 on 2023-04-06 20:36

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0037_listitemtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="listelementitem",
            name="tag",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="tag",
                to="elements.listitemtag",
                verbose_name="Tag",
            ),
        ),
    ]
