# Generated by Django 4.1.3 on 2023-04-06 21:30

import api.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elements", "0038_listelementitem_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listelementitem",
            name="primary",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Primary List Text",
                max_length=300,
                null=True,
                verbose_name="Primary List Text",
            ),
        ),
        migrations.AlterField(
            model_name="listelementitem",
            name="secondary",
            field=api.customs.CustomCharField(
                blank=True,
                help_text="Secondary List Text",
                max_length=300,
                null=True,
                verbose_name="Secondary List Text",
            ),
        ),
        migrations.CreateModel(
            name="CardElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Description (Optional)",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    api.customs.CustomPositiveIntegerField(
                        default=0, verbose_name="Page Appearance Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    api.customs.CustomCharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        default="Unordered",
                        help_text="Card Size Type",
                        max_length=10,
                        verbose_name="Card Size Type",
                    ),
                ),
                (
                    "icon",
                    api.customs.CustomCharField(
                        blank=True,
                        help_text="Select Card Icon (Optional)",
                        max_length=40,
                        null=True,
                        verbose_name="Card Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Card Image (Optional)",
                        null=True,
                        upload_to="cardimage",
                        verbose_name="Card Image (Optional)",
                    ),
                ),
                (
                    "header",
                    api.customs.CustomCharField(
                        blank=True,
                        help_text="Card Header Text (Optional)",
                        max_length=100,
                        null=True,
                        verbose_name="Card Header Text (Optional)",
                    ),
                ),
                (
                    "subheader",
                    api.customs.CustomCharField(
                        blank=True,
                        help_text="Card Subheader Text (Optional)",
                        max_length=100,
                        null=True,
                        verbose_name="Card Subheader Text (Optional)",
                    ),
                ),
                (
                    "primary",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Primary Card Text",
                        max_length=1000,
                        null=True,
                        verbose_name="Primary Card Text",
                    ),
                ),
                (
                    "secondary",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Secondary Card Text (Optional)",
                        max_length=1000,
                        null=True,
                        verbose_name="Secondary Card Text (Optional)",
                    ),
                ),
                (
                    "author",
                    api.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Element",
                "verbose_name_plural": "Card Elements",
                "ordering": ["-id"],
            },
        ),
    ]
