# Generated by Django 4.1.3 on 2023-04-10 19:31

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0039_alter_listelementitem_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listelementitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="process_images", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="listelement",
            name="type",
            field=api.customs.CustomCharField(
                choices=[
                    ("Unordered", "Unordered"),
                    ("Ordered", "Ordered"),
                    ("Icon", "Icon"),
                    ("Image", "Image"),
                ],
                default="Unordered",
                help_text="List Type",
                max_length=10,
                verbose_name="List Type",
            ),
        ),
    ]
