# Generated by Django 4.1.3 on 2023-04-13 02:25

import api.customs
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elements", "0042_listitemtag_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="listelementitem",
            name="author",
            field=api.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
    ]
