# Generated by Django 4.1.3 on 2023-04-19 04:22

import api.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0043_listelementitem_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardelement",
            name="button_toggle",
            field=api.customs.CustomBooleanField(
                default=False, help_text="Button Toggle", verbose_name="Button Toggle"
            ),
        ),
        migrations.AddField(
            model_name="cardelement",
            name="share_toggle",
            field=api.customs.CustomBooleanField(
                default=False, help_text="Share Toggle", verbose_name="Share Toggle"
            ),
        ),
        migrations.AlterField(
            model_name="cardelement",
            name="type",
            field=api.customs.CustomCharField(
                choices=[
                    ("Tile", "Tile"),
                    ("Standard", "Standard"),
                    ("Dense", "Dense"),
                ],
                default="Standard",
                help_text="Card Size Type",
                max_length=10,
                verbose_name="Card Size Type",
            ),
        ),
    ]
