# Generated by Django 4.1.3 on 2023-04-30 20:36

import api.customs
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0045_alter_listelement_type_alter_textelement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="textelement",
            name="header",
            field=api.customs.CustomForeignKeyField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_query_name="text_header",
                to="elements.headerelement",
                verbose_name="Header",
            ),
        ),
        migrations.AlterField(
            model_name="cardelement",
            name="type",
            field=api.customs.CustomCharField(
                choices=[
                    ("Tile", "Tile"),
                    ("Standard", "Standard"),
                    ("Dense", "Dense"),
                ],
                default="Standard",
                help_text="Card Type",
                max_length=10,
                verbose_name="Card Type",
            ),
        ),
        migrations.AlterField(
            model_name="textelement",
            name="text",
            field=api.customs.CustomTextField(
                blank=True,
                help_text="Text",
                max_length=5000,
                null=True,
                verbose_name="Text",
            ),
        ),
    ]
